### ISSUE TITLE
openssh private key prevents normal connection

### ISSUE THREAD

**Issue by brainchild0** [Xpra-org/xpra#3383] opened 2021-12-09 16:32 UTC
# Description

The client is unable to establish an SSH connection to a remote host.

The console output appears below.

The problem may be resolved by appending the command line with `--ssh=ssh`, however, this solution is not available from the graphical connection launcher.

---

```
$ xpra start ssh://user@host
Gtk-Message: 11:23:34.193: Failed to load module "appmenu-gtk-module"
2021-12-09 11:23:34,275 Xpra GTK3 X11 client version 4.2.3-r12 64-bit
Gtk-Message: 11:23:34.279: Failed to load module "appmenu-gtk-module"
2021-12-09 11:23:34,425  running on Linux Linuxmint 20.2 uma
2021-12-09 11:23:34,426  window manager is 'Mutter (Muffin)'
Gtk-Message: 11:23:35.205: Failed to load module "appmenu-gtk-module"
2021-12-09 11:23:35,250 GStreamer version 1.16.2 for Python 3.8.10 64-bit
2021-12-09 11:23:35,281 created unix domain socket '/run/user/1000/xpra/clients/XXXXX-181824'
2021-12-09 11:23:35,344 No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
2021-12-09 11:23:35,508 Warning: vendor 'Intel' is greylisted,
2021-12-09 11:23:35,508  you may want to turn off OpenGL if you encounter bugs
2021-12-09 11:23:35,600 OpenGL enabled with Mesa Intel(R) Iris(R) Plus Graphics (ICL GT2)
2021-12-09 11:23:35,651 Connected (version 2.0, client OpenSSH_8.2p1)
2021-12-09 11:23:35,761 Exception: key cannot be used for signing
2021-12-09 11:23:35,763 Traceback (most recent call last):
2021-12-09 11:23:35,763   File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 2109, in run
2021-12-09 11:23:35,763     handler(self.auth_handler, m)
2021-12-09 11:23:35,763   File "/usr/lib/python3/dist-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
2021-12-09 11:23:35,763     sig = self.private_key.sign_ssh_data(blob)
2021-12-09 11:23:35,763   File "/usr/lib/python3/dist-packages/paramiko/agent.py", line 418, in sign_ssh_data
2021-12-09 11:23:35,763     raise SSHException("key cannot be used for signing")
2021-12-09 11:23:35,764 paramiko.ssh_exception.SSHException: key cannot be used for signing
2021-12-09 11:23:35,764 
2021-12-09 11:23:35,764 SSH agent key 'MD5:3d:83:cb:11:70:21:4e:af:2b:24:f2:07:75:11:60:94' rejected for user 'user'
2021-12-09 11:23:35,764 agent authentication failed, tried 1 key
2021-12-09 11:23:35,765 Warning: private key '/home/user/.ssh/id_rsa'
2021-12-09 11:23:35,765  this file seems to be using OpenSSH's own format
2021-12-09 11:23:35,765  please convert it to something more standard (ie: PEM)
2021-12-09 11:23:35,765  so it can be used with the paramiko backend
2021-12-09 11:23:35,765  or switch to the OpenSSH backend with '--ssh=ssh'
2021-12-09 11:23:35,765 Error: cannot load private key '/home/user/.ssh/id_rsa'
```

# Reproduction

The problem appears to be caused by a private key in the user's local directory that had been created by OpenSSH. Creating a private key with OpenSSH is suggested to reproduce the problem.

# System

- **Server:**
  - **OS:** Linux Mint 20.2
  - **Application:** Xpra v4.2.3-r12
- **Client:**
  - **OS:** Linux Mint 20.2
  - **Application:** Xpra v4.2.3-r12

**Comment by totaam** [comment] 2021-12-10 05:07
Probably a duplicate of #3330, please try the latest 4.3 beta builds.

**Comment by brainchild0** [comment] 2021-12-10 05:50
Please reread carefully, and consider reopening.

It is not a duplicate of the other issue.

**Comment by totaam** [comment] 2021-12-10 06:13
Sorry, the correct duplicate is likely to be #2307

**Closed by totaam** 2021-12-10 06:13 UTC
Labels: bug

**Comment by brainchild0** [comment] 2021-12-10 06:37
I tested with the 2021-12-09 nightly. The problem does not resolve. Please see updated description with new version information.

**Comment by totaam** [comment] 2021-12-10 07:17
Then there's nothing we can do, please follow the (now updated: 93aefb7) warning message and switch back to plink for ssh transport.

**Comment by brainchild0** [comment] 2021-12-10 07:21
I'm confused. Why did you reference this issue, occurring under Linux, in a commit that is described as related to running under Windows?

Why not just leave the issue open, instead of closing based on a judgment that a solution is impossible?

**Comment by totaam** [comment] 2021-12-10 07:24
> Why not just leave the issue open..

Leaving issues open forever helps no-one, this bug occurs in a library (paramiko).
If and when it does get fixed, we can update the ticket accordingly.
Until then, there is zero action to be taken in xpra.

**Comment by brainchild0** [comment] 2021-12-10 07:36
I suggest leaving and open and writing a note about waiting for a solution upstream, even encouraging someone to submit a report to the relevant project. You already have an *upstream* label, which is good.

Closing simply because no immediate action is available just increases the chances that  more reporting work will occur in the future. 

Leaving open helps  discovery of the existing report by the right person at the right time, and helps coordination of activities.  If the upstream projects creates a solution while this issue is open, then someone may see this report, and test again, or offer a submission that takes advantage of improvements in the upstream project.

**Comment by totaam** [comment] 2021-12-10 07:51
No, you misunderstand.
The fix has already been applied in paramiko 2.7 and has been deployed for years, your distribution is just shipping a version (2.6.0) that does not have it: https://packages.ubuntu.com/focal/python3-paramiko

And as stated above, those kinds of bugs never ever get fixed by Debian / Ubuntu.
Feel free to bug them, but this is a waste of time.

**Comment by brainchild0** [comment] 2021-12-10 08:03
Thanks for the explanation.

Would you consider supporting an environment variable that sets the SSH client? Otherwise, everyone running a distribution with this issue is unable to use the graphical launcher.

**Comment by totaam** [comment] 2021-12-10 08:06
> Otherwise, everyone running a distribution with this issue is unable to use the graphical launcher.

No need. This should work (untested):
```shell
echo "ssh=ssh -x" >> /home/antoine/.config/xpra/xpra.conf
```

**Comment by brainchild0** [comment] 2021-12-10 08:09
It would help keep the workaround more cleanly separated from the core configuration, but I can use your suggestion.
