### ISSUE TITLE
Xpra 4.4.3-r0-1 on Debian prevents Python upgrade to 3.11

### ISSUE THREAD

**Issue by fpoto** [Xpra-org/xpra#3755] opened 2023-02-02 14:08 UTC
xpra : Depends: python3 (< 3.11) but 3.11.1-2 is to be installed

**Comment by totaam** [comment] 2023-02-02 14:22
Looks like an exact duplicate of #3752.
If you are on bookworm, just update again.

**Closed by totaam** 2023-02-02 14:22 UTC
Labels: bug

**Comment by fpoto** [comment] 2023-02-02 16:59
It does not look like the same.  The issue here is that Xpra requires python3 (<< 3.11)

Debian wants to upgrade Python to 3.11.1-2, so all packages requiring Python 3.11 cannot be installed unless Xpra is removed

**Comment by totaam** [comment] 2023-02-03 03:12
@fpoto it is exactly like #3752:
```
 xpra : Depends: python3 (< 3.11) but 3.11.1-2 is to be installed
```
My guess is that despite running an unstable ABI distro, you only have the stable repository installed.
Please install the beta channel for beta distros.

**Comment by fpoto** [comment] 2023-02-13 13:32
Thanks. That was indeed the case. If possible, it would be clearer if in the download page only the link relative to the beta version was present next to the Bookworm Debian distribution

**Comment by adamhotep** [comment] 2023-02-28 19:33
FYI, installing the beta unstable xpra package on Debian testing (currently Bookworm) required me to run `apt install libproc2-0/unstable` to manage that dependency.

To make more permanent, add this to `/etc/apt/preferences.d/xpra.pref`:
```debprefs
Explanation: https://github.com/Xpra-org/xpra/issues/3755
Package: xpra
Pin: release a=unstable,o=xpra.org
Pin-Priority: 500

Explanation: Xpra needs this
Package: libproc2-0
Pin: release a=unstable
Pin-Priority: 500
```

**Comment by totaam** [comment] 2023-03-01 05:09
@adamhotep these have nothing to do with this ticket, do they?
The `libproc2` issue was introduced by @adamnew123456 in https://github.com/Xpra-org/xpra/commit/6a41cd90ec1171be8afd0c11e82fc1ad80981c1c and AFAICT, this has nothing to do with bookworm ABI.
The ssh issue is not clear, as for the syntax change, it can be found here: #3599

This ticket is closed.

**Comment by adamhotep** [comment] 2023-03-01 20:00
@totaam: My comment was related to the official workaround of upgrading to the beta channel, which won't work without this change. I could not upgrade my Debian Testing (Bookworm) system to Xpra 5.0 beta without pulling libproc2-0 4.0.3-1 from unstable. Xpra wouldn't install with libproc2-0 4.0.2-3 from testing. The reason for that is the Xpra dependencies:
```
$ apt depends xpra |grep libproc2-0
  Depends: libproc2-0 (>= 2:4.0.3)
$ apt policy libproc2-0
libproc2-0:
  Installed: 2:4.0.3-1
  Candidate: 2:4.0.3-1
  Version table:
 *** 2:4.0.3-1 500
          1 http://deb.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
     2:4.0.2-3 500
        500 http://deb.debian.org/debian testing/main amd64 Packages
        100 https://http.kali.org/kali kali-rolling/main amd64 Packages
$
```
(Priority 500 comes from my previous comment's xpra.perf config)

I can file a separate ticket for the ssh username collision issue.

**Comment by adamnew123456** [comment] 2023-03-02 02:17
@adamhotep 

> FYI, installing the beta unstable xpra package on Debian testing (currently Bookworm) required me to run apt install libproc2-0/unstable to manage that dependency.

I think the freeze around testing / Bookworm either has started already or is supposed to soon. So while you could get away with using the unstable repo against testing before, they're going to drift more and more the closer Bookworm gets to release.

AIUI, there's nothing to gain by running unstable packages against testing since @totaam builds the same code into the testing packages as the unstable ones. So using https://raw.githubusercontent.com/Xpra-org/xpra/master/packaging/repos/bookworm/xpra-beta.sources is recommended for testing systems.

**Comment by totaam** [comment] 2023-03-02 05:20
@adamhotep like @adamnew123456 said above, you are using the wrong repository for your distribution.
Please follow the download instructions:
https://github.com/Xpra-org/xpra/wiki/Download#-for-debian-based-distributions
The latest package for `bookworm` correctly depends on `libproc2-0 (>= 2:4.0.2)`.

**Comment by adamhotep** [comment] 2023-03-30 15:18
Yes, confirmed. It works when I've got the proper `testing` repo.
