### ISSUE TITLE
Another "Error creating launcher form" "Unknown OpenSSL error"

### ISSUE THREAD

**Issue by rrama** [Xpra-org/xpra#3763] opened 2023-02-14 10:38 UTC
**Describe the bug**
Xpra crashes when opening the connection window (launcher form) with an "Unknown OpenSSL error" (Traceback in screenshot below).

**To Reproduce**
1.  Launch the Xpra client on Mac.
1.  Press the "Connect" button.

**System Information (please complete the following information):**
 -  Server OS: N/A
 -  Client OS: MacBook Pro with Apple M1 Max running macOS 13.1
 -  Xpra Server Version: N/A
 -  Xpra Client Version: 4.4.3

**Additional context**
I have tried running both:
`xpra --ssh=ssh --ssh-upgrade=no gui` and `xpra --ssh=ssh --ssh-upgrade=no launcher` as suggested in #3701
I have also tried directly opening a `.xpra` file with the following lines at the bottom:
```
ssh=ssh
ssh-upgrade=no
```

I have screenshotted the error, since I don't seem to be able to copy & paste it.
<img width="599" alt="Screenshot 2023-02-14 at 10 31 33" src="https://user-images.githubusercontent.com/2266832/218709977-307b97ac-b9fb-4e7d-be4c-3fdd0f909355.png">
The trace looks different, hence why I am opening a new issue, but if it is the same then feel free to mark it as a duplicate and I'll post there.

**Comment by totaam** [comment] 2023-02-14 13:56
Just like #3757, this is an exact duplicate of #3701.
You can find workarounds there.

**Closed by totaam** 2023-02-14 13:56 UTC
Labels: bug, duplicate
