### ISSUE TITLE
v4.4.3 has an erroneous CUDA_BIN reference in setup.py and won't build.

### ISSUE THREAD

**Issue by erykoff** [Xpra-org/xpra#3693] opened 2022-11-28 01:20 UTC
**Describe the bug**

The automatic update to 4.4.3 on conda-forge failed because `CUDA_BIN` is undefined on line 2216, https://github.com/Xpra-org/xpra/blob/v4.4.3/setup.py#L2216

This line doesn't seem to be in master, I haven't traced how it got here to the release tag, but it looks broken to me since it's an undefined variable unless `nvidia_ENABLED` is set.

See e.g. https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/619002/logs/35

**To Reproduce**
1. server command
2. client command
3. specific action to trigger the bug

**System Information (please complete the following information):**
 - Server OS: [e.g. RHEL 8.x]
 - Client OS: [e.g. Windows 10]
 - Xpra Server Version [e.g. 4.2.3]
 - Xpra Client Version [e.g. 4.3]

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment] 2022-11-28 07:35
Caused by 23b2c55737ca8b368197f01cc547d5439c84b862, should be fixed in the commit above.
Note: this only affected builds without the nvidia codecs - which is why none of our builds failed.

**Closed by totaam** 2022-11-28 07:35 UTC
Labels: bug

**Comment by erykoff** [comment] 2022-11-28 17:22
Thank you for the quick fix, that did the trick!

**Comment by gitbxf4** [comment] 2023-01-24 07:12
I'm not sure why, but to successfully build xpra version 4.4.3 (downloaded on 1/22/2023) on an up to date Debian unstable machine, I also had to delete the line

    `add_data_files(CUDA_BIN,` ["fs/share/xpra/cuda/README.md"])`

from setup.py.
