### ISSUE TITLE
Symlink for Debian Testing distribution

### ISSUE THREAD

**Issue by adamhotep** [Xpra-org/xpra#3528] opened 2022-04-21 01:50 UTC
Like many people, I use [Debian Testing](https://www.debian.org/releases/testing/) as a [rolling release](https://en.wikipedia.org/wiki/Rolling_release). As Debian nears a release, the `testing` repository freezes and enters a hardening phase (so it's "rolling" with a stutter). When the release comes out, a new codename comes out and the `testing` repository is linked to it. Users that assign their APT sources to `testing` are automatically upgraded. In contrast, people who entered that as `bullseye` were locked in; they started on `testing` before its release and are now on `stable` (and when Bookworm comes out, they'll be on `oldstable`).

Xpra does not have a "testing" link to the "next" release codename, so I was stuck on "bullseye" until I found my system auto-uninstalled xpra due to its dependency on python < 3.10.4. I had to discover this issue and then update `/etc/apt/sources.list.d/xpra.list` to the new codename. (... and then realize that Xpra isn't yet compiled for even that configuration ... and lacks a `deb-src` repository for me to compile and install it in a manner that APT would update with your official builds later).

Please create and maintain a symlink for Debian `testing`. I believe that's all you need to do. This should point at `bookworm` until that releases, then it should point at the new testing release codename. Repeat this every Debian release.

**Comment by totaam** [comment] 2022-04-21 05:12
I have added 3 symlinks to the repositories:
```shell
ln -sf buster oldstable
ln -sf bullseye stable
ln -sf bookworm testing
```

Since this is a manual process, don't expect those symlinks to be updated exactly when Debian makes the switch - there will be some lag.

As for the Python 3.10 issue, this is almost an exact duplicate of #3525: use the beta channel for beta distros.

**Closed by totaam** 2022-04-21 05:12 UTC
Labels: enhancement

**Comment by adamhotep** [comment] 2022-04-21 17:31
This works, though APT gives this (harmless) warning:
```
W: Conflicting distribution: https://xpra.org testing InRelease (expected testing but got bookworm)
```

Solving that warning (noting the caveat below) involves one more tiny tweak: Change the `Suite` from `bookworm` to `testing`:
```diff
--- Release.old	2022-04-21 01:34:07.467045186 -0400
+++ Release	2022-04-21 01:34:49.662923802 -0400
@@ -1,6 +1,6 @@
 Origin: xpra.org
 Label: Debian
-Suite: bookworm
+Suite: testing
 Codename: bookworm
 Architectures: amd64
 Components: main
```
This should say `Suite: testing` (for both bookworm and testing, so no need to adjust the symlink solution). Reference [Xpra bookworm/Release file](https://xpra.org/dists/bookworm/Release) vs [Debian bookworm/Release file](http://ftp.debian.org/debian/dists/bookworm/Release).

**⚠️ Warning!** This might make things a little more painful when Debian releases bookworm ahead of when you update this file. I'm not sure of the consequences or of how other third-party repositories manage this.

**Comment by adamhotep** [comment] 2022-04-22 02:20
Ah, one more symlink is needed for sid == unstable. This one will never need to be updated. Changing to `Suite: unstable` will prevent the warning noted above without any risks.

**Comment by totaam** [comment] 2022-04-22 06:01
Done for the beta repo now:
```shell
$ grep Suite: */Release
bionic/Release:Suite: bionic
bookworm/Release:Suite: testing
bullseye/Release:Suite: stable
buster/Release:Suite: oldstable
focal/Release:Suite: focal
hirsute/Release:Suite: hirsute
impish/Release:Suite: impish
jammy/Release:Suite: jammy
oldstable/Release:Suite: oldstable
sid/Release:Suite: unstable
stable/Release:Suite: stable
stretch/Release:Suite: stretch
testing/Release:Suite: testing
unstable/Release:Suite: unstable
xenial/Release:Suite: xenial
```

**Comment by adamhotep** [comment] 2023-08-02 22:15
Hi, @totaam! A new Debian release came out, so the symlinks now need updating to `trixie`.

The error isn't easily understood, so I also wanted to dump it here for people to find it in their web searches:

```
Get:16 https://xpra.org/beta testing InRelease [4,739 B]
Get:17 https://xpra.org/beta testing/main amd64 Packages [39.0 kB]
Err:17 https://xpra.org/beta testing/main amd64 Packages
  File has unexpected size (41080 != 39035). Mirror sync in progress? [IP: 78.129.163.65 443]
  Hashes of expected file:
   - Filesize:39035 [weak]
   - SHA512:19789588bbb166860ae3f82c502d092a8bfb2f83bfb6f96435d99a23e068e03a8b9af5c6068f68583c6082e862da7f219b2fa16115d6742c1bb28f2c80d59b6b
   - SHA256:97e26c375c991940f12080faf553fe9da5d5ed5e3e4d057591b7fad9a0016295
   - SHA1:91c020ea313304709050bc0f5e391f16f46991f1 [weak]
   - MD5Sum:2e659cfc03b4f150e7d14ffb0df1f2bb [weak]
  Release file created at: Fri, 28 Jul 2023 11:58:28 +0000
Fetched 4,739 B in 4s (1,231 B/s)
Reading package lists... Done
E: Failed to fetch https://xpra.org/beta/testing/main/binary-amd64/Packages.bz2  File has unexpected size (41080 != 39035). Mirror sync in progress? [IP: 78.129.163.65 443]
   Hashes of expected file:
    - Filesize:39035 [weak]
    - SHA512:19789588bbb166860ae3f82c502d092a8bfb2f83bfb6f96435d99a23e068e03a8b9af5c6068f68583c6082e862da7f219b2fa16115d6742c1bb28f2c80d59b6b
    - SHA256:97e26c375c991940f12080faf553fe9da5d5ed5e3e4d057591b7fad9a0016295
    - SHA1:91c020ea313304709050bc0f5e391f16f46991f1 [weak]
    - MD5Sum:2e659cfc03b4f150e7d14ffb0df1f2bb [weak]
   Release file created at: Fri, 28 Jul 2023 11:58:28 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by totaam** [comment] 2023-08-03 07:56
Done. Thanks!
