### ISSUE TITLE
Ubuntu Focal has a hard time starting gnome-terminal

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3077] opened 2021-04-09 06:12 UTC
Welcome from the Focal side!

```console
$ xpra start --use-display=auto :2
WARNING: low display number: 2
 You are attempting to run the xpra server
 against a low X11 display number: ':2'.
 This is generally not what you want.
 You should probably use a higher display number
 just to avoid any confusion and this warning message.
Entering daemon mode; any further errors will be reported to:
  /run/user/1000/xpra/display-:2-20210409-090136.log
$ vfb failed to start, exiting

$ bat /run/user/1000/xpra/display-:2-20210409-090136.log
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1
 key2021-04-09 09:01:37,755 cannot access python uinput module:
2021-04-09 09:01:37,756  No module named 'uinput'
(EE) 
Fatal server error:
(EE) Server is already active for display 2
    If this server is no longer running, remove /tmp/.X2-lock
    and start again.
(EE) 
2021-04-09 09:01:37,764 
2021-04-09 09:01:37,764 Xvfb command has terminated! xpra cannot continue
2021-04-09 09:01:37,764  if the display is already running, try a different one,
2021-04-09 09:01:37,764  or use the --use-display flag
2021-04-09 09:01:37,764  full command: Xvfb +extension GLX +extension Composite -screen 0  8192x4096x24+32 -nolisten tcp -noreset -auth $XAUTHORITY  -dpi 96
2021-04-09 09:01:37,764 
$ 
```

It seems that I have a leftover display from yesterday:
```console
$ ps faxu | grep ':2 '
sntentos   13488  0.0  0.2 1738464 173048 ?      Ssl  Απρ08   0:00  \_ Xvfb-for-Xpra-:2 +extension GLX +extension Composite -screen 0 8192x4096x24+32 -nolisten tcp -noreset -auth /run/user/1000/gdm/Xauthority -dpi 96 :2
sntentos  275899  0.0  0.0  11580   664 pts/4    S+   09:11   0:00      \_ grep --color=auto :2 
$ bat display-\:2-20210408-160201.log 
2021-04-08 16:02:02,660 cannot access python uinput module:
2021-04-08 16:02:02,660  No module named 'uinput'
xpra main error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 126, in main
    return run_mode(script_file, err, options, args, mode, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 401, in run_mode
    return do_run_mode(script_file, error_cb, options, args, mode, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 432, in do_run_mode
    return run_server(script_file, error_cb, options, args, mode, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 2158, in run_server
    return do_run_server(error_cb, options, mode, script_file, args, desktop_display, progress_cb)
  File "/usr/lib/python3/dist-packages/xpra/scripts/server.py", line 822, in do_run_server
    no_gtk()
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 2322, in no_gtk
    raise Exception("the Gtk module is already loaded: %s" % Gtk)
Exception: the Gtk module is already loaded: <GtkProxyModule <IntrospectionModule 'Gtk' from '/usr/lib/x86_64-linux-gnu/girepository-1.0/Gtk-3.0.typelib'>>
```

If I start xterm first and then gnome-terminal, all is good!

Note that forcing does not help:
```console
$ xpra --use-display=yes start :2
$ cat /run/user/1000/xpra/display-\:2-20210409-105347.log 
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 key2021-04-09 10:53:50,137 Error: failed to connect to display :2
2021-04-09 10:53:50,137  could not connect to X server on display ':2' after 3 seconds
```

**Comment by stdedos** [comment] 2021-04-09 08:07
Also note that shadowing is broken too similarly:
```console
$ cat /run/user/1000/xpra/display-\:0-20210409-104008.log 
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 key2021-04-09 10:40:11,233 Error: failed to connect to display :0
2021-04-09 10:40:11,233  could not connect to X server on display ':0' after 3 seconds
```

**Comment by totaam** [comment] 2021-04-09 08:49
> $ xpra start --use-display=auto :2

FYI: `use-display=auto` is the default
```shell
$ xpra showconfig | grep use-display
use-display = 'auto'
```

> `Invalid MIT-MAGIC-COOKIE-1 key...`

The problem here is that it's hard to distinguish between a display that isn't running and one we can't access because of `XAUTHORITY` problems: in both cases, we can't connect to it..

My guess is that something (logged out? switched user?) modified `$XAUTHORITY` or its permissions making it impossible for xpra to access those displays.

> `Exception: the Gtk module is already loaded..`

This one is very strange. Could it be similar to #3073?
We verify that Gtk is not already loaded (it shouldn't be) after initializing dbus.

This is something that we do on all platforms. And it never fails elsewhere.


> If I start xterm first and then gnome-terminal, all is good!

I don't understand this bit. Your command lines don't have `gnome-terminal` in them.


I've just tried repeatedly on Ubuntu Focal and I cannot get it to misbehave. (as usual..)
What am I missing? Do you have reproducible steps?

**Comment by stdedos** [comment] 2021-04-09 09:42
> The problem here is that it's hard to distinguish between a display that isn't running and one we can't access because of `XAUTHORITY` problems: in both cases, we can't connect to it..
> 
> My guess is that something (logged out? switched user?) modified `$XAUTHORITY` or its permissions making it impossible for xpra to access those displays.

Nothing should have explicitly happened. Server's :0 was already locked to begin with, and I suspect no-one is touching my workstation remotely.

Is there a way to recover the sessions? Terminate them cleanly?
I don't mind lowering security around non-:0, as the workstation itself "should be secure", and xpra's monitors shouldn't be accessible from the outside (right?)

---

> This one is very strange. Could it be similar to #3073?

I don't see something that would help identify the issue; this seems to be active.
OP says he'll downgrade to v3; I was there yesterday on Xenial/Unity.
It will be interesting to see his combination's results.

---

> I don't understand this bit. Your command lines don't have `gnome-terminal` in them.

I didn't think it was worth copy-pasting the session from which I got you all this output 😀
That's how I jump-started my station.

> I've just tried repeatedly on Ubuntu Focal and I cannot get it to misbehave. (as usual..)

As usual 😢 

> What am I missing? Do you have reproducible steps?

Step 1: Take my Xenial
Step 2: Update it to Focal
Step 3: Success! You broke xpra
(PLEASE don't do it 😛 I am just joking)

Connection is, as usual, initiated via the Win10-17134.1792 / xpra v4.2-r28802 (578263a94) endpoint

**Comment by totaam** [comment] 2021-04-09 12:24
> Is there a way to recover the sessions? Terminate them cleanly?

Yes. The big hammer: `xhost +` might help xpra get access to them again.

The fix above should avoid:
> ```
>   File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 2322, in no_gtk
>    raise Exception("the Gtk module is already loaded: %s" % Gtk)
> ```
>
Which can happen when the display exists and we use `use-display=auto` (the default).
This may explain why xpra couldn't access the session.
(not sure why I didn't hit it though - looks like it should have bugged!)

**Comment by stdedos** [comment] 2021-04-09 12:29
> > Is there a way to recover the sessions? Terminate them cleanly?
> 
> Yes. The big hammer: `xhost +` might help xpra get access to them again.

Still Invalid MIT-MAGIC-COOKIE-1 key 😕

**Comment by stdedos** [comment] 2021-04-09 14:59
> Also note that shadowing is broken too similarly:
> 
> ```
> $ cat /run/user/1000/xpra/display-\:0-20210409-104008.log 
> Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 key2021-04-09 10:40:11,233 Error: failed to connect to display :0
> 2021-04-09 10:40:11,233  could not connect to X server on display ':0' after 3 seconds
> ```

Forgot to check this one with `xhost +`

**Comment by totaam** [comment] 2021-04-11 13:24
There are two parts to this:
* which `$XAUTHORITY` file was used
* allowing access (ie: `xhost +`)

It should be possible to rescue the session by re-creating the file or allowing access.
xpra uses the `$XAUTHORITY` value which is often set by the login manager (ie: gdm). Unfortunately, it is possible for that file to disappear.
We have support code for using our own private one (#1776) but since this restricts access to the `$DISPLAY` and users expect to be able to do `DISPLAY=:N dosomething` from any login session, this was never enabled by default.

I am closing because the two bugs are fixed and sessions should not get wedged.

**Closed by totaam** 2021-04-11 13:24 UTC
