### ISSUE TITLE
Supplied Xdummy command line in /etc/xpra/conf.d/55_server_x11.conf doesn't work

### ISSUE THREAD

**Issue by Giraut** [Xpra-org/xpra#3125] opened 2021-05-11 18:21 UTC
This doesn't work:

```
xvfb = /usr/bin/Xorg -noreset -nolisten tcp \
       +extension GLX +extension RANDR +extension RENDER \
       -auth $XAUTHORITY \
       -logfile auto/Xorg.${DISPLAY}.log \
       -configdir ${XDG_RUNTIME_DIR}/.xpra/xorg.conf.d/$PID \
       -config /etc/xpra/xorg.conf
```

This does:

```
xvfb = /usr/bin/Xorg -noreset -nolisten tcp \
       +extension GLX +extension RANDR +extension RENDER \
       -auth $XAUTHORITY \
       -logfile ${XDG_RUNTIME_DIR}/xpra/Xorg.${DISPLAY}.log \
       -config /etc/xpra/xorg.conf
```

The former results in this getting dumped in `/var/run/user/<uid>/xpra/:<display>.log`:

```
failure on /tmp/.X11-unix/X100: [Errno 2] No such file or directory: '/tmp/.X11-unix/X100'
xpra initialization error:
 failed to create the Xorg log directory 'auto': [Errno 13] Permission denied: 'auto'
```

and the -configdir argument also points to a nonexistent location, but is apparently unused, so it can be dispensed with.

Tested with the vanilla Xdummy driver as well as the patched one.

Xpra v4.2-r29076-1
Xdummy v1:0.3.8-5+xpra1

Incidentally, rendering with Xdummy seems much better than with xvfb - faster and almost no artifacts. More importantly (for me anyway, that's the reason I'm trying it), Teams for Linux seems to display more or less correctly every time, whereas with xvfb, it crashes the Xpra server a third of the time, and renders as a black pane another third of the time.

Probably GL-related, not sure what's going on exactly, but I figured you might be interested: Teams is a turd of an application that does its own rendering with zero regard for efficiency and apparently as little X compatibility as it can get away with. So it's a good stress test for Xpra.

**Comment by totaam** [comment] 2021-05-12 05:33
What distro?

> and the -configdir argument also points to a nonexistent location, but is apparently unused, so it can be dispensed with.

It can be used, ie with uinput device mode.

>  `failed to create the Xorg log directory 'auto': [Errno 13] Permission denied: 'auto'`

Odd. Perhaps you have a space in your `$XDG_RUNTIME_DIR`?
Does the commit above help? (adds quotes around the dir value)
What's the exact command it tried to run? (you can see if by adding `-d screen` to your server command line)

> Incidentally, rendering with Xdummy seems much better than with xvfb

Interesting.
> .. it crashes the Xpra server a third of the time ..

Do you have steps to reproduce. Xpra should not crash, no matter vfb is in use, no matter how badly the applications are behaving.
> Probably GL-related..

I thought that unless you used virtualgl, both Xvfb and Xdummy used the same software GL renderer.

**Comment by Giraut** [comment] 2021-05-12 07:25
> What distro?

Linux Mint 20.
 
> It can be used, ie with uinput device mode.

Ah right, yes, I don't use uinput. Still, at least on my machine, there is no .xpra directory in $XDG_RUNTIME_DIR - unless it creates it before running the server, I didn't check

> Odd. Perhaps you have a space in your `$XDG_RUNTIME_DIR`?

Nope. XDG_RUNTIME_DIR == /run/user/1000 on my machine.

I'm fairly sure it's trying to create that "auto" directory in the current directory, which is... whatever it is when it starts, I didn't figure it out, and it's root-owned. Might be / or /etc/something

> What's the exact command it tried to run? (you can see if by adding `-d screen` to your server command line)

> > Incidentally, rendering with Xdummy seems much better than with xvfb
> 
> Interesting.
> 
> > .. it crashes the Xpra server a third of the time ..
> 
> Do you have steps to reproduce. Xpra should not crash, no matter vfb is in use, no matter how badly the applications are behaving.

I'll try all that tonight. I'm at work right now.

> > Probably GL-related..
> 
> I thought that unless you used virtualgl, both Xvfb and Xdummy used the same software GL renderer.

Well, I'll see what the exact difference is. But there's a clear difference in speed, and with the Xvfb server, in certain applications (mostly running in VirtualBox), there are artifacts line black lines when scrolling too fast that aren't there with Xdummy. And of course Teams works.

I'll see what's what with the crash also. I'll report back.

**Comment by totaam** [comment] 2021-05-12 12:33
> Still, at least on my machine, there is no `.xpra` directory in `$XDG_RUNTIME_DIR`

`$XDG_RUNTIME_DIR/xpra` (no dot) should be created when you start a server.
The Xorg `configdir` does not have to exist.

> `failed to create the Xorg log directory 'auto'`
> ..
> I'm fairly sure it's trying to create that "auto" directory in the current directory

It should be trying to create the log directory where the log file is going to go.
Again, `-d screen` should give us the details.

> .. there are artifacts line black lines when scrolling too fast that aren't there with Xdummy

It would be interesting to see if these lines are caused by Xvfb itself (applications not painting properly) or if it is xpra that is not behaving properly.
Disabling `scroll` encoding might resolve some of those problems: `--encodings=rgb,webp,jpeg,png,h264,vp8,vp9`

**Comment by totaam** [comment] 2021-07-13 14:18
@Giraut Is still a problem with 4.2.1?

**Comment by callegar** [comment] 2021-11-04 21:25
I am also seeing the
```
failed to create the Xorg log directory 'auto': [Errno 13] Permission denied: 'auto'
```
when trying to use Xdummy in place of Xvfb.

Using `-logfile ${XDG_RUNTIME_DIR}/xpra/Xorg.${DISPLAY}.log` also fails, because Xorg complains about using -logfile with elevated privilege.

This happens on kubuntu 20.04. Any clue?

**Comment by totaam** [comment] 2021-11-05 03:27
You guys have installed the dummy driver right?
On Debian / Ubuntu that's `xserver-xorg-video-dummy`.

On a 20.04 test VM, I did:
* `apt-get purge xpra`
* `apt-get install xpra xserver-xorg-video-dummy`
* modified `/etc/xpra/conf.d/55_server_x11.conf` to use `/usr/lib/xorg/Xorg ...`

Start xpra, everything works.
I have not tried doing the same thing via an ssh login. First things first.

It does create the logfile in "./auto/.$DISPLAY.log" and yes, we should fix that. But that's not fatal here.

**Comment by callegar** [comment] 2021-11-05 09:23
Looks like I have it installed:
```
Package: xserver-xorg-video-dummy
Status: install ok installed
Priority: optional
Section: x11
Installed-Size: 37
Maintainer: Antoine Martin <antoine@xpra.org>
Architecture: amd64
Version: 1:0.3.8-6+xpra1
```
As soon as I am in the physical place where the machine is, I'll test again, but it is not so important. I just wanted to try Xdummy because of an issue I was experiencing with Xvfb and `vglrun` (so I wanted to make a comparison) but I have already solved it.

Must say that my machine has a very old nvidia card that requires patched legacy drivers on the Ubuntu HWE kernels, so I may have something weird in the Xorg configuration.

**Comment by totaam** [comment] 2021-11-05 14:31
Let's close this for now.

**Closed by totaam** 2021-11-05 14:31 UTC
Labels: question
