### ISSUE TITLE
Xpra window loses focus when switching desktop

### ISSUE THREAD

**Issue by fpoto** [Xpra-org/xpra#3645] opened 2022-10-11 13:44 UTC
With 4.4-r0-1 with Mate desktop under Debian, on the (remote) client  I launch xpra and open an Emacs window on the server. If I switch desktop and then go back to the Xpra Emacs window, the cursor is hollow rather than full. I can move the cursor it using the mouse, but the keyboard has no effect.

Downgrading to 4.3.2-r0-1 on the (remote) client solves the problem. Server is still 4.4-r0-1

The command I use on the client is:

```
xpra start ssh://my.box.at.office/7 --ssh="ssh -i ~/.ssh/id_rsa" \
	 --attach=auto --use-display=auto --dpi=86 \
	 --speaker=on --env=XPRA_CUTTER_THRESHOLD=0 \
	 --border=\#CCCC00 --start=editor
```

 Up-to-date Debian testing (bookworm) on both server and client

**Comment by totaam** [comment] 2022-10-11 14:03
This looks like an exact duplicate of #3596 - the problem is limited to Debian clients.
Can you specify your client window manager in that other ticket please?

**Closed by totaam** 2022-10-11 14:03 UTC
Labels: bug
