### ISSUE TITLE
No application shown in the start menu

### ISSUE THREAD

**Issue by oeway** [Xpra-org/xpra#3227] opened 2021-07-29 17:56 UTC
Perhaps this is not a bug of xpra itself, but I cannot get the application menu (with the html5 client) working with Ubuntu 18.04.

In the log I see:
```
2021-07-29 17:51:17,245 Error parsing xdg menu data:
2021-07-29 17:51:17,245  ParsingError in file '/etc/xdg/menus/kde-debian-menu.menu', File not found
2021-07-29 17:51:17,246  this is either a bug in python-xdg,
```
Full log here: [startup-log-xpra.txt](https://github.com/Xpra-org/xpra/files/6902585/startup-log-xpra.txt)

Could you please take a look?

**Comment by oeway** [comment] 2021-07-29 22:26
I already tried to set `XDG_MENU_PREFIX ` to `gnome-` as mentioned here https://github.com/Xpra-org/xpra/issues/2174. But  it doesn't seem to help.

**Comment by totaam** [comment] 2021-07-30 05:07
You may find some clues in #3083 and #3108.
ie: you may need to source `/etc/profile` or just `/etc/profile.d/apps-bin-path.sh`.

**Comment by oeway** [comment] 2021-07-31 17:25
It looks like I don't have these files, maybe because I didn't configure the desktop environment correctly ([Dockerfile](https://github.com/imjoy-team/imjoy-hybrid-desktop/blob/xpra/binder/Dockerfile)). Is there a easy way that I can add custom application menu?

**Comment by totaam** [comment] 2021-08-01 03:43
> Is there a easy way that I can add custom application menu?

With xpra 4.3:
```
xpra start --env=XPRA_MENU_LOAD_APPLICATIONS=/usr/local/share/applications
```
Or you can try setting `XDG_CONFIG_DIRS` to point to your custom menus (should work with all xpra versions).

**Comment by totaam** [comment] 2021-11-06 09:20
I am unable to reproduce the problem and this is not an xpra bug so I am closing this ticket.

FYI: loading is now much faster: #3326

**Closed by totaam** 2021-11-06 09:20 UTC
