### ISSUE TITLE
start-desktop always hangs

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3220] opened 2021-07-24 05:44 UTC
updated to new 4.3-10.r29499. f33 and f34. needing desktop facilities in the near future. invocation:
`xpra start-desktop :19 --start-child=mwm --resize-display=1856x1024`

invariably, the resulting desktop hangs sometime shortly after `xpra attach`, always first indicated by failure to respond to mouse. generally, `mwm` (motif window manager) will let me get as far as opening a terminal window from its menu, but then trying to resize the window or move it around the desktop results in hang. breaking the attach and asking `xpra list`, the session is clearly confused, usually noted as "dead" or "unknown" state, which gets cleaned up, and another `xpra list` shows no sessions. nonetheless, the `Xorg` for the session persists, which it is necessary to kill manually.

the problem is not `mwm` as window manager. i've also tried `twm`, as well as full DE with `mate-session`.

**Comment by totaam** [comment] 2021-07-24 07:49
`mwm` and other **ancient** window managers like `twm` still use a [XGrabServer](https://tronche.com/gui/x/xlib/window-and-session-manager/XGrabServer.html) which makes it impossible for xpra to talk to the X11 server.
This is unfixable by design.

> which it is necessary to kill manually

You can also do:
* `xpra recover`
* `xpra clean-displays`

**Comment by karlkleinpaste** [comment] 2021-07-25 00:31
fair enough, i'll avoid `mwm` and `twm` from now on. my usual DE is MATE, and i can start a desktop with `mate-session` instead. but though it lasts longer, it too eventually gives up and dies every time, with `Xorg` remaining orphaned, whether i'm using `marco` or `compiz` as WM. (it takes perhaps 10 or 15 minutes of random usage of the desktop before it goes catatonic and `xpra attach` goes into retry hell.) are these WMs also guilty of (mis)use of XGrabServer? if so, what WM does not use it?

**Comment by totaam** [comment] 2021-07-25 03:42
> i can start a desktop with `mate-session` instead. but though it lasts longer, it too eventually gives up and dies every time

That should not happen. All recent (say 2000 onwards!) window managers avoiding using `XGrabServer` so whatever is happening is probably not the window manager's fault.

Although `mate-session` is a bit jumpy when moving windows - something I will investigate separately, it's running stable for me.

@karlkleinpaste is there anything specific I can do to trigger the problems you're seeing?
A particular application or sequence of actions?

**Comment by karlkleinpaste** [comment] 2021-07-25 13:44
there are 3 machines where i (want to) use remote xpra desktop, being utility/monitoring systems where i don't really need much, which is why i would have preferred a minimal desktop using just `mwm` or `twm`. `mate-session` begins well, and my normal pattern is to start a couple `mate-terminal` windows plus several gadgets (`oclock`, `xload`, `zenity --info` to mark the display with the hostname because it's easy to forget which machine i'm seeing, `nvidia-settings`), and thereafter it's just occasional observations of the desktop with ordinary shell commands e.g. `tail -f` on a logfile, or `ps` or `top` to see what's busy, occasionally `mate-system-monitor` for a wider view. i couldn't say that there's any specific action that causes it; when i've experimented, it's commonly that i've tried to move a window or begun to type a new command when it would stop, the log says "not responding, drawing spinners," and then retry hell is entered.

i just tried using `gnome-session` instead, and the result is oddly psychotic, but differing on f33 vs. f34: on f33 (gnome 3.38), i get what appears to be a normal desktop except that i cannot use the top bar at all: there is no reaction to mousing on Activities on the left or the system icons on the right. on f34 (gnome 40), i get a magnified desktop, apparently 2:1, where mouse movement moves the visible pane around, and again the top bar does not react to the mouse. i did not keep using these long enough to see `xpra` disconnects.

using `ssh ph xpra start-desktop :19 --start-child=gnome-session --resize-display=1856x1024`

(fyi, if it might matter: my main machine is f33, the other 3 machines are f34.)

**Comment by totaam** [comment] 2021-07-25 15:02
> i just tried using `gnome-session` instead, and the result is oddly psychotic

I believe that this is gnome using the default software opengl for rendering.
You would get better result with a real opengl driver via `virtualgl` for such desktop environments.

> i get a magnified desktop, apparently 2:1

Hmm, that's a different problem. Looks like some scaling setting is misconfigured somewhere.

FWIW: I've had a local session running all day and finally just closed it this evening since I couldn't trigger any problems.

**Comment by karlkleinpaste** [comment] 2021-07-25 15:19
> You would get better result with a real opengl driver via virtualgl for such desktop environments.

in fact i use VGL constantly and almost everywhere. no difference for me in this case with `--start-child='vglrun gnome-session'` except that, with `VGL_LOGO=1`, i also get the bottom right-hand corner logo.

> Looks like some scaling setting is misconfigured somewhere.

then it's a bad default setting, because i had literally never invoked gnome-session on that machine until this morning.

but not an xpra-specific problem, i'm sure.

**Comment by totaam** [comment] 2021-11-06 09:24
Closing because `mwm` and `twm` cannot be supported.
Other DEs, including `gnome-shell` should work, even with software OpenGL.
If not then I will need some steps to reproduce the problem.

**Closed by totaam** 2021-11-06 09:24 UTC
Labels: bug, server, X11
