### ISSUE TITLE
connection failed: 'NoneType' object has no attribute 'asbytes' (Apple M1)

### ISSUE THREAD

**Issue by Bresenham** [Xpra-org/xpra#3402] opened 2021-12-26 23:06 UTC
Executing

`xpra start-desktop ssh:user@server --exit-with-children --start-child=xfce4-session`

leads to the following output:

```
(Xpra:27826): Gtk-CRITICAL **: 00:03:51.955: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
2021-12-27 00:03:52,083 Xpra GTK3 client version 4.3-r12 64-bit
2021-12-27 00:03:52,122  running on Mac OS X 10.16
get_icon_pixbuf(xpra.png)
Traceback (most recent call last):
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/gtk_common/gtk_util.py", line 559, in get_icon_pixbuf
    return GdkPixbuf.Pixbuf.new_from_file(icon_filename)
gi.repository.GLib.GError: gdk-pixbuf-error-quark: Unable to load image-loading module: /Applications/Xpra.app/Contents/Resources/bin/../@executable_path/../Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: dlopen(/Applications/Xpra.app/Contents/Resources/bin/../@executable_path/../Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so, 0x0001): tried: '/Applications/Xpra.app/Contents/Resources/lib/libpixbufloader-png.so' (no such file), '/Applications/Xpra.app/Contents/Resources/bin/../@executable_path/../Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so' (no such file), '/usr/local/lib/libpixbufloader-png.so' (no such file), '/usr/lib/libpixbufloader-png.so' (no such file) (5)
2021-12-27 00:03:53,998 GStreamer version 1.18.5 for Python 3.9.9 64-bit
2021-12-27 00:03:54,019 created unix domain socket '/Users/mgaul/.xpra/clients/Maximilians-Air-27826'
2021-12-27 00:03:54,031 Error importing png decoder (dec_spng)
2021-12-27 00:03:54,031  dlopen(/Applications/Xpra.app/Contents/Resources/lib/python/xpra/codecs/spng/decoder.cpython-39-darwin.so, 0x0002): Library not loaded: /Users/macos/gtk/inst/lib/libspng.0.dylib
  Referenced from: /Applications/Xpra.app/Contents/Resources/lib/python3.9/xpra/codecs/spng/decoder.cpython-39-darwin.so
  Reason: tried: '/Applications/Xpra.app/Contents/Resources/lib/libspng.0.dylib' (no such file), '/Users/macos/gtk/inst/lib/libspng.0.dylib' (no such file), '/usr/local/lib/libspng.0.dylib' (no such file), '/usr/lib/libspng.0.dylib' (no such file)
2021-12-27 00:03:54,120 OpenGL_accelerate module loaded
2021-12-27 00:03:54,133 Using accelerated ArrayDatatype
2021-12-27 00:03:54,449 OpenGL enabled with Apple M1
2021-12-27 00:04:14,551 Connected (version 2.0, client OpenSSH_8.4p1)
xpra initialization error:
 connection failed: 'NoneType' object has no attribute 'asbytes'
```

I downloaded xpra from here: https://xpra.org/dists/osx/x86_64/Xpra.pkg

Can someone help me to fix this error?

**Comment by totaam** [comment] 2021-12-27 09:09
There are actually 3 errors in that command output:
* `gdk-pixbuf-error-quark: Unable to load image-loading module: ... /usr/lib/libpixbufloader-png.so`

This one should already have been solved by dc5a99287744696a3976ec156a510e249dc7e710.
I'll have to double check it. This should not be fatal.
* `Error importing png decoder (dec_spng)`

Fixed by 15922eacb50b16cfb28424949e640d4592bb50ea. This should not be fatal either.

> `connection failed: 'NoneType' object has no attribute 'asbytes'`

The only place where we call `asbytes` on anything in the whole codebase is in the `sshfp` module:
https://github.com/Xpra-org/xpra/blob/600f30e8940775cbeb2b69ced9b4950f1019bd15/xpra/net/sshfp.py#L33-36
The `key` value is checked earlier:
https://github.com/Xpra-org/xpra/blob/e58b25c071698846c098890a72f66671db6955cf/xpra/net/ssh.py#L364
And cannot be `None`.
Even if it was, the `sshfp` check function traps all exceptions so I don't see how the error could cause a connection failure.

Perhaps you could run your command line with `-d ssh` and see if that gives us more useful information.

**Comment by totaam** [comment] 2021-12-27 14:36
I have uploaded a new build (4.3.1-r24) in the beta area: https://xpra.org/beta/MacOS/
This one fixes the `libspng` error (as per above), but I am not able to reproduce the `gdk-pixbuf-error-quark` error or the `asbytes` one.
Please include the `-d ssh` output if the problem still occurs.

**Comment by Bresenham** [comment] 2021-12-27 14:58
@totaam Thank you so much! Works perfectly now :)

**Closed** 2021-12-27 15:37 UTC
Labels: bug, network, macos

**Comment by totaam** [comment] 2023-05-06 15:54
@Bresenham we now have beta arm64 builds that should be able to run on M1 and later, they require MacOS 12:
https://github.com/Xpra-org/xpra/wiki/Download#-macos
