### ISSUE TITLE
Mouse wheel scroll event triggers twice for each scrolling

### ISSUE THREAD

**Issue by Vssblt** [Xpra-org/xpra#3406] opened 2021-12-30 08:41 UTC
**Bug**
Mouse wheel scroll event triggers twice for each scrolling.

**To Reproduce**
1. `/usr/bin/xpra proxy :20 --socket-dirs=/xxx/xxx/xxx/xxx --daemon=yes --bind-tcp=0.0.0.0:12008 --tcp-auth=allow`
2. `/usr/bin/xpra start :1024 --tcp-auth=password:value=1 --daemon=no --start-child=/xxx/xxx/xxx/xxx --exit-with-children=yes` # socket-dirs same to xpra proxy
3. Scroll the mouse wheel in qt application. `qscrollbar` scroll event trigger twice for each wheel scrolling. I don’t think it’s a qt problem, I take this as an example.

**System Information:**
 - Server OS: Ubuntu 20.04 in docker
 - Client OS: Chrome/Firefox on Ubuntu 20.04
 - Xpra Server Version: v4.3-r0
 - Xpra Client Version: xpra-html5 v5.0

**Comment by totaam** [comment] 2022-01-03 14:32
@Vssblt Is the proxy really needed?
Does the bug also occur with the python client?

**Comment by Vssblt** [comment] 2022-01-04 01:25
Minimum trigger condition:
```
xpra start :1024 --tcp-auth=allow --daemon=no --start-child=/usr/bin/xterm -d mouse --bind-tcp=0.0.0.0:12008    #server
xpra attach tcp://xxx@10.68.30.14:12008/1024                   # python client
```

The bug occurred with the python client and html5 client.

Server log when html5 client connected and scrolled mouse one time: 
```
2022-01-04 01:09:37,549 process_button_action(WebSocket(ws socket: 172.17.0.2:12008 <- 10.68.30.159:38886), ['button-action', 1, 5, True, (2312, 682), ('mod2',), ()])
2022-01-04 01:09:37,550 do_process_mouse_common(WebSocket(ws socket: 172.17.0.2:12008 <- 10.68.30.159:38886), 1, (2312, 682), -1)
2022-01-04 01:09:37,550 xtest_fake_button(5, True)
2022-01-04 01:09:37,550 process_button_action(WebSocket(ws socket: 172.17.0.2:12008 <- 10.68.30.159:38886), ['button-action', 1, 5, False, (2312, 682), ('mod2',), ()])
2022-01-04 01:09:37,551 do_process_mouse_common(WebSocket(ws socket: 172.17.0.2:12008 <- 10.68.30.159:38886), 1, (2312, 682), -1)
2022-01-04 01:09:37,551 xtest_fake_button(5, False)
2022-01-04 01:09:37,551 process_button_action(WebSocket(ws socket: 172.17.0.2:12008 <- 10.68.30.159:38886), ['button-action', 0, 5, True, (2312, 682), ('mod2',), ()])
2022-01-04 01:09:37,551 do_process_mouse_common(WebSocket(ws socket: 172.17.0.2:12008 <- 10.68.30.159:38886), 0, (2312, 682), -1)
2022-01-04 01:09:37,552 xtest_fake_button(5, True)
2022-01-04 01:09:37,552 process_button_action(WebSocket(ws socket: 172.17.0.2:12008 <- 10.68.30.159:38886), ['button-action', 0, 5, False, (2312, 682), ('mod2',), ()])
2022-01-04 01:09:37,552 do_process_mouse_common(WebSocket(ws socket: 172.17.0.2:12008 <- 10.68.30.159:38886), 0, (2312, 682), -1)
2022-01-04 01:09:37,552 xtest_fake_button(5, False)
```

Server log when python client connected and scrolled mouse one time:
```
2022-01-04 01:18:50,470 process_button_action(Protocol(tcp socket: 172.17.0.2:12008 <- 10.68.30.159:39406), ['button-action', 2, 5, True, (1928, 865, 1928, 865), ('mod2',), ()])
2022-01-04 01:18:50,471 do_process_mouse_common(Protocol(tcp socket: 172.17.0.2:12008 <- 10.68.30.159:39406), 2, (1928, 865, 1928, 865), -1)
2022-01-04 01:18:50,471 xtest_fake_button(5, True)
2022-01-04 01:18:50,471 process_button_action(Protocol(tcp socket: 172.17.0.2:12008 <- 10.68.30.159:39406), ['button-action', 2, 5, False, (1928, 865, 1928, 865), ('mod2',), ()])
2022-01-04 01:18:50,472 do_process_mouse_common(Protocol(tcp socket: 172.17.0.2:12008 <- 10.68.30.159:39406), 2, (1928, 865, 1928, 865), -1)
2022-01-04 01:18:50,475 xtest_fake_button(5, False)
2022-01-04 01:18:50,475 process_button_action(Protocol(tcp socket: 172.17.0.2:12008 <- 10.68.30.159:39406), ['button-action', 2, 5, True, (1928, 865, 1928, 865), ('mod2',), ()])
2022-01-04 01:18:50,476 do_process_mouse_common(Protocol(tcp socket: 172.17.0.2:12008 <- 10.68.30.159:39406), 2, (1928, 865, 1928, 865), -1)
2022-01-04 01:18:50,476 xtest_fake_button(5, True)
2022-01-04 01:18:50,477 process_button_action(Protocol(tcp socket: 172.17.0.2:12008 <- 10.68.30.159:39406), ['button-action', 2, 5, False, (1928, 865, 1928, 865), ('mod2',), ()])
2022-01-04 01:18:50,477 do_process_mouse_common(Protocol(tcp socket: 172.17.0.2:12008 <- 10.68.30.159:39406), 2, (1928, 865, 1928, 865), -1)
2022-01-04 01:18:50,477 xtest_fake_button(5, False)
```

Other logs when server init
```
$ xpra start :1024 --tcp-auth=allow --daemon=no --start-child=/usr/bin/xterm -d mouse --bind-tcp=0.0.0.0:12008

Warning: running as root
Warning: the 'start-child' option is used,
 but 'exit-with-children' is not enabled,
 you should just use 'start' instead
2022-01-04 01:22:46,130 created tcp socket '0.0.0.0:12008'
2022-01-04 01:22:46,171 debug enabled for xpra.platform.xposix.gui / ('posix', 'mouse')
2022-01-04 01:22:46,198 debug enabled for xpra.server.mixins.input_server / ('mouse',)
2022-01-04 01:22:46,202 debug enabled for xpra.x11.x11_server_core / ('x11', 'server', 'mouse')
2022-01-04 01:22:46,203 debug enabled for xpra.x11.x11_server_base / ('x11', 'server', 'mouse')
2022-01-04 01:22:46,203 debug enabled for xpra.x11.server / ('x11', 'mouse')
2022-01-04 01:22:46,205 init_virtual_devices({'pointer': {'name': "Xpra Virtual Pointer b'fv9wnYRC4seC'", 'uinput': <uinput.Device object at 0x7fc2a5c05070>, 'device': b'/dev/input/event19'}, 'touchpad': {}}) got pointer={'name': "Xpra Virtual Pointer b'fv9wnYRC4seC'", 'uinput': <uinput.Device object at 0x7fc2a5c05070>, 'device': b'/dev/input/event19'}, touchpad={}
2022-01-04 01:22:46,205 debug enabled for xpra.x11.uinput_device / ('x11', 'server', 'mouse')
2022-01-04 01:22:46,206 XInput version 2.2
2022-01-04 01:22:46,206 UInput.wheel_motion(4, 1.0000) REL_WHEEL: 0+30=30, will emit 30
2022-01-04 01:22:46,206 xtest_fake_motion(0, 100, 100)
2022-01-04 01:22:46,206 UInputPointerDevice.move_pointer(0, 200, 200)
2022-01-04 01:22:46,206 X11Keyboard.query_pointer=100, 100
2022-01-04 01:22:46,206 delta(100, 100)=100, 100
2022-01-04 01:22:46,206 pointer device emulation using UInput pointer device /dev/input/event19
2022-01-04 01:22:46,235 serving html content from '/usr/share/xpra/www'
2022-01-04 01:22:46,236 wrote pid 4363 to '/run/xpra/1024/server.pid'
2022-01-04 01:22:46,245 Warning: socket directory '/run/xpra/1024'
2022-01-04 01:22:46,245  expected permissions 0o700 but found 0o750
2022-01-04 01:22:46,245 created unix domain socket '/run/user/0/xpra/179b2b5f1053-1024'
2022-01-04 01:22:46,245 created unix domain socket '/run/xpra/179b2b5f1053-1024'
2022-01-04 01:22:46,246 created unix domain socket '/root/.xpra/179b2b5f1053-1024'
2022-01-04 01:22:46,246 created unix domain socket '/run/xpra/1024/socket'
2022-01-04 01:22:46,246 xvfb pid=4020
2022-01-04 01:22:46,293 D-Bus notification forwarding is available
2022-01-04 01:22:46,313 pulseaudio server started with pid 4374
2022-01-04 01:22:46,313  private server socket path:
2022-01-04 01:22:46,313  '/run/xpra/1024/pulse/pulse/native'
W: [pulseaudio] main.c: This program is not intended to be run as root (unless --system is specified).
E: [autospawn] core-util.c: XDG_RUNTIME_DIR (/run/xpra/1024/pulse) is not owned by us (uid 0), but by uid 1000! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
W: [autospawn] lock-autospawn.c: Cannot access autospawn lock.
E: [pulseaudio] main.c: Failed to acquire autospawn lock

Warning: running as root

(Xpra:4363): Gtk-CRITICAL **: 01:22:46.406: gtk_widget_realize: assertion 'widget->priv->anchored || GTK_IS_INVISIBLE (widget)' failed
2022-01-04 01:22:46,518 waiting for initialization thread to complete
2022-01-04 01:22:46,519 xpra is ready.
2022-01-04 01:22:46,531 watching for applications menu changes in:
2022-01-04 01:22:46,531  '/usr/share/applications'
2022-01-04 01:22:46,536 Warning: webcam forwarding is disabled
2022-01-04 01:22:46,536  the virtual video directory '/sys/devices/virtual/video4linux' was not found
2022-01-04 01:22:46,536  make sure that the 'v4l2loopback' kernel module is installed and loaded
2022-01-04 01:22:46,536  or use the 'webcam=no' option
2022-01-04 01:22:46,537 found 0 virtual video devices for webcam forwarding
Warning: failed to query pulseaudio using 'pactl info'
 Connection failure: Connection refused
 pa_context_connect() failed: Connection refused
2022-01-04 01:22:46,568 Warning: lpinfo command failed and returned 1
2022-01-04 01:22:46,569  command used: '/usr/sbin/lpinfo --make-and-model Generic PDF Printer -m'
Warning: failed to query pulseaudio using 'pactl info'
 Connection failure: Connection refused
 pa_context_connect() failed: Connection refused
2022-01-04 01:22:46,589 Warning: lpinfo command failed and returned 1
2022-01-04 01:22:46,589  command used: '/usr/sbin/lpinfo --make-and-model Generic PostScript Printer -m'
2022-01-04 01:22:46,590 printer forwarding enabled using pdf
2022-01-04 01:22:46,595 started command '/usr/bin/xterm' with pid 4394
2022-01-04 01:22:46,604 GStreamer version 1.16.2 for Python 3.8.10 64-bit
2022-01-04 01:22:46,685 Warning: failed to query pulseaudio using 'pactl info'
2022-01-04 01:22:46,685  Connection failure: Connection refused
2022-01-04 01:22:46,686  pa_context_connect() failed: Connection refused
2022-01-04 01:22:46,694  cannot load enc_nvjpeg (nvjpeg encoder)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/codecs/loader.py", line 52, in codec_import_check
    ic =  __import__(class_module, {}, {}, classnames)
  File "xpra/codecs/nvjpeg/encoder.pyx", line 8, in init xpra.codecs.nvjpeg.encoder
  File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/__init__.py", line 51, in <module>
    del os.environ[envkey]
  File "/usr/lib/python3.8/os.py", line 691, in __delitem__
    raise KeyError(key) from None
KeyError: 'OPENBLAS_MAIN_FREE'
2022-01-04 01:22:46,710 vp8 codec encoding error 8: b'Invalid parameter'
2022-01-04 01:22:46,710 vpx: vp8 encoding failed: data is empty and there are no delayed frames!
2022-01-04 01:22:46,710 vpx: vp9 encoding failed: 'vp9'
2022-01-04 01:22:46,711 vpx: all the codecs have failed! (vp8, vp9)
2022-01-04 01:22:46,840 CUDA initialization (this may take a few seconds)
2022-01-04 01:22:46,955 CUDA 11.2.0 / PyCUDA 2021.1, found 1 device:
2022-01-04 01:22:46,955   + GeForce RTX 3090 @ 0000:65:00.0 (memory: 98% free, compute: 8.6)
2022-01-04 01:22:47,009 NVidia driver version 460.91.3
2022-01-04 01:22:47,079  device GeForce RTX 3090 is not supported: cannot open encoding session: This indicates that an invalid struct version was used by the client., 0 contexts are in use
2022-01-04 01:22:47,079 no valid NVENC devices found
2022-01-04 01:22:47,185 Warning: no VAAPI support
2022-01-04 01:22:47,186  vaapi device context not found
2022-01-04 01:22:47,218 X11Keyboard.query_pointer=(100, 100)
2022-01-04 01:22:47,222 Warning: UInput pointer device /dev/input/event19 failed verification
2022-01-04 01:22:47,222  expected pointer at (200, 200), now at (100, 100)
2022-01-04 01:22:47,222  usign XTest fallback
2022-01-04 01:22:47,225 Warning: enc_nvjpeg failed its self test
2022-01-04 01:22:47,225  failed to select a cuda device
2022-01-04 01:22:47,326 251.4GB of system memory
2022-01-04 01:22:47,523 Warning: pulseaudio has terminated shortly after startup.
2022-01-04 01:22:47,523  pulseaudio is limited to a single instance per user account,
2022-01-04 01:22:47,523  and one may be running already for user 'root'.
2022-01-04 01:22:47,523  To avoid this warning, either fix the pulseaudio command line
2022-01-04 01:22:47,524  or use the 'pulseaudio=no' option.
2022-01-04 01:22:47,748 loaded 14 start menu entries from 3 sub-menus in 1.2 seconds
2022-01-04 01:22:47,821 OpenGL is supported on display ':1024'
2022-01-04 01:22:47,821  using 'llvmpipe (LLVM 12.0.0, 256 bits)' renderer
2022-01-04 01:22:47,832 started command 'ibus-daemon --xim --verbose --replace --panel=disable --desktop=xpra --daemonize' with pid 4524
```

**Comment by Vssblt** [comment] 2022-01-04 08:14
I probably know where the html client problem is.
xpra-html5 version 5.0
`Window.js:243` and `Client.J's: 215` have registered mouse wheel event twice. 
`div.addEventListener('wheel', on_mousescroll, false);`
I commented out one of them and it ran correctly.

**Comment by totaam** [comment] 2022-01-04 08:48
@Vssblt Thanks!
Does this work for you with the html5 client:
https://github.com/Xpra-org/xpra-html5/commit/5a8da12661ec65843da2078fb25fdce76fe0620e

I will still have to figure out the python client problem.
I suspect this may be related to #3127 - perhaps we get both a `SMOOTH` and a regular scroll event?
The client's output with `-d mouse` should show us what events it is receiving.

---

BTW, your numpy version is borked:
```
KeyError: 'OPENBLAS_MAIN_FREE'
```

**Comment by totaam** [comment] 2022-01-04 13:38
I'm not seeing double events, this is what `-d mouse` shows:
```
smooth scroll event: <Gdk.EventScroll object at 0x7f6fed2f03b0 (void at 0x560170e3a6e0)>
send_wheel_delta(1, 6, 0.0000, (0,)) precise wheel=False, modifiers=['mod2'], pointer=[4659, 949, 582, 645]
send_wheel_delta(1, 5, -1.0000, (0,)) precise wheel=False, modifiers=['mod2'], pointer=[4659, 949, 582, 645]
button packet: ['button-action', 1, 5, True, [4659, 949, 582, 645], ['mod2'], []]
button packet: ['button-action', 1, 5, False, [4659, 949, 582, 645], ['mod2'], []]
wheel_event(1, 0.0, -1.0, 0) new deltas=0.0,0.0
```
A single smooth scroll event triggers a pair of button packets (one down, one up).

And this is also what `xev` sees:
```
ButtonPress event, serial 34, synthetic NO, window 0xc00001,
    root 0x50e, subw 0x0, time 110075694, (461,274), root:(4393,415),
    state 0x10, button 4, same_screen YES

ButtonRelease event, serial 34, synthetic NO, window 0xc00001,
    root 0x50e, subw 0x0, time 110075711, (461,274), root:(4393,415),
    state 0x810, button 4, same_screen YES
```

Same as when running natively.

**Comment by totaam** [comment] 2022-02-24 07:39
@Vssblt I can't reproduce with the python client, so I am closing this issue.
Feel free to re-open if you can reproduce it.

**Closed by totaam** 2022-02-24 07:39 UTC
Labels: bug, question
