### ISSUE TITLE
Some Java Applications work properly. No Mouse reaction and wrong rendering

### ISSUE THREAD

**Issue by waldi5001** [Xpra-org/xpra#3146] opened 2021-05-30 11:47 UTC
Hello,
I try to start a java application. From the first view it works. Command is: 
`xpra start --start="java -jar /home/xyz/Documents/abc-0.10-SNAPSHOT.jar" --bind-tcp=0.0.0.0:10000`
When I connect with the html 5 client
`http://127.0.0.1:10000/connect.html`
or via socket and the xpra_launcher, there are usability issues. It seems a bit of #3076. I attached the logfile, and hope it helps.

whats going wrong: 
- After selection of a DropDown content, the selection is not viewable.
- There is no reaction from a mouse click viewable
- initial JInternalFrames are not visible.

```
Xpra Version 4.2
Python 3.8, 64bit
revision 0
commit g11293f0e3 from v4.2.x branch
with 0 local changes
2021-05-18 16:16
using Cython 0.29.14
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
```

I can't not provide you the application to test, but can give you further logfiles. Can maybe a small video help?
[xpraLogs.tar.gz](https://github.com/Xpra-org/xpra/files/6566127/xpraLogs.tar.gz)

**Comment by totaam** [comment] 2021-05-30 12:14
Sorry, but I don't have the time to debug via log files.
I need a sample application.

**Comment by waldi5001** [comment] 2021-05-30 16:24
yes, fair point. I've created a small test application. If you play around with window of the combobox (try resize, move), you can see that something is wrong.

Here you can download it, please feel free to specify a different location: https://mega.nz/file/EpI32CDK#0uSD0HwGIyPQ_lbx_S3eEfb5M4o4Bkgwv38B7jo_Y50

you have to run it via java 8 
```
java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.272-b10, mixed mode)
```
and the xpra call is:
`xpra start --start="java -jar /home/fk/Documents/xpra-swing-test/target/xpra-swing-test-1.0-SNAPSHOT.jar" --bind-tcp=0.0.0.0:10000`

Hope I can help you.

**Comment by totaam** [comment] 2021-05-31 01:47
Please attach the source to this ticket, not a binary in a location that will end up as 404 eventually.

**Comment by waldi5001** [comment] 2021-05-31 10:11
Hello Antoine,
the problem is that the sample is built with the [Synthetica L&F](http://www.javasoft.de/synthetica/). You cannot run the code standalone without the synthetica dependencies and to download the dependencies, you have to buy a license. I build a jar which includes all the necessary dependencies. Without the synthetica L&F, the problem doesn't occur.

**Comment by totaam** [comment] 2021-05-31 10:18
So the download you just provided is very likely to be illegal.
I am deleting the comment.
I don't have the time to spin up VMs to run untrusted code for proprietary toolkits.

**Comment by waldi5001** [comment] 2021-05-31 10:22
For distribution, it isn't illegal. For that reason my sample hasn't a licence key in it. From your point of view you try a demo.

**Comment by waldi5001** [comment] 2021-05-31 10:25
I can can agree and understand your point of view, but I don't know what I have to look for. If you want you can give me hints and I can provide you logs or something else.

**Comment by totaam** [comment] 2021-05-31 14:01
If the application runs OK with the python client then this ticket should be migrated to the https://github.com/Xpra-org/xpra-html5 project.

Then to debug, try running the server with `-d metadata,state` or perhaps even the big hammer `-d window` and collecting the log output of when the problematic window is shown.
Debugging the html5 client is quite difficult.

**Comment by waldi5001** [comment] 2021-05-31 17:25
I've recorded a small session with the problem and uploaded it to youtube. The logfiles from that session are attached.

https://youtu.be/2z_6xmDaoik

[xpra-logs.tar.gz](https://github.com/Xpra-org/xpra/files/6571600/xpra-logs.tar.gz)

The problem exists in the html5 and native client. The debug options are -d metadata,state

**Comment by totaam** [comment] 2021-05-31 17:38
Your log file is almost empty - it's the wrong one:
```
$ cat S255319.log
failed to setup tcp socket on 0.0.0.0:10000 [Errno 98] Address already in use
```

**Comment by waldi5001** [comment] 2021-05-31 17:52
Sorry. Hmm only the 1.log has content. 

[1.tar.gz](https://github.com/Xpra-org/xpra/files/6571701/1.tar.gz)

**Comment by totaam** [comment] 2021-05-31 18:13
Why use tar on a single file? You could just have attached it here directly.
And this file has everything in it, instead of just _the log output of when the problematic window is shown_ as requested.

From your video, it looks like the problem is from the window geometry, the toolkit is probably making some assumptions about the window manager and getting it wrong. Something similar to #705 perhaps.
I suggest you have a look at that ticket and try a few things:
* changing `wm-name`
* changing Java SDK

See also https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs for the missing details.

**Comment by waldi5001** [comment] 2021-06-01 18:54
Today I tested a bit
- with `xpra start-desktop` the rendering problem doesn't occur.
- with `xpra start-desktop` and the Synthetica and feel, a window header is showed, but with a click of maximize the window, no action is visible.
   - A test with java 11 is not possible, the L&F only run with java 8. But 1.8.0_272 is a actual supported version.
- with `xpra start-desktop` and the default look and feel, no window header and therefore no close, maximize.... buttons are visible. The Combobox dialog has also no header. [MainWindow.txt](https://github.com/Xpra-org/xpra/files/6579832/MainWindow.txt) and [bugreport-1.zip](https://github.com/Xpra-org/xpra/files/6579851/bugreport-1.zip)
  - This test with java 11 has the same result
- changing wm-name like `XPRA_NET_WM_NAME=Sawfish` or `XPRA_NET_WM_NAME=fvwm[2]` has no effect
- The problem showed in the video seems in correlation with a modal dialog, also with the license dialog. 
- Catch the logfile when the problem with the dialog occur [1.txt](https://github.com/Xpra-org/xpra/files/6579944/1.txt)  

[sessionInfo.txt](https://github.com/Xpra-org/xpra/files/6579887/sessionInfo.txt)

**Comment by totaam** [comment] 2021-06-02 04:03
> with `xpra start-desktop` and the Synthetica and feel, a window header is showed, but with a click of maximize the window, no action is visible
> with `xpra start-desktop` and the default look and feel, no window header and therefore no close, maximize.... buttons are visible

You need to run a window manager. ie: `--start=fluxbox`

> A test with java 11 is not possible, the L&F only run with java 8

That's really not a good sign.
I am closing this ticket again as I won't be spending time on this.

**Closed by totaam** 2021-06-02 04:03 UTC
Labels: geometry

**Comment by waldi5001** [comment] 2021-06-02 08:50
You are noticed that there is also a problem **without** Synthetica?:
> with xpra start-desktop **and the default look and feel**, no window header and therefore no close, maximize.... buttons are visible

**Comment by totaam** [comment] 2021-06-02 09:00
This has nothing to do with Synthetica.
The window manager draws the window decorations. No window manager, no window decorations.
