### ISSUE TITLE
MacOS xpra dies with Traceback

### ISSUE THREAD

**Issue by SkyperTHC** [Xpra-org/xpra#3728] opened 2023-01-07 08:54 UTC
**Describe the bug**
Python exits with Traceback.

**To Reproduce**
1.  Either install from .pkg or `brew update & brew install xpra`
2. `xpra start ssh ://foo@bar`

```
grep: /usr/share/locale/locale.alias: No such file or directory
xpra main error:
Traceback (most recent call last):
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 142, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 451, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 462, in do_run_mode
    return run_remote_server(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 1902, in run_remote_server
    params = parse_display_name(error_cb, opts, display_name, cmdline)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/parsing.py", line 495, in parse_display_name
    ssh = parse_ssh_option(opts.ssh)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/parsing.py", line 674, in parse_ssh_option
    import paramiko
  File "paramiko/__init__.pyc", line 22, in <module>
  File "paramiko/transport.pyc", line 132, in <module>
  File "paramiko/transport.pyc", line 206, in Transport
  File "paramiko/kex_curve25519.pyc", line 30, in is_available
  File "cryptography/hazmat/primitives/asymmetric/x25519.pyc", line 39, in generate
  File "cryptography/hazmat/backends/openssl/__init__.pyc", line 6, in <module>
  File "cryptography/hazmat/backends/openssl/backend.pyc", line 63, in <module>
  File "cryptography/hazmat/bindings/openssl/binding.pyc", line 228, in <module>
  File "cryptography/hazmat/bindings/openssl/binding.pyc", line 188, in init_static_locks
  File "cryptography/hazmat/bindings/openssl/binding.pyc", line 176, in _ensure_ffi_initialized
  File "cryptography/hazmat/bindings/openssl/binding.pyc", line 90, in _openssl_assert
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=126353445, lib=15, reason=524325, reason_text=b'error:07880025:common libcrypto routines::reason(524325)')])
```

**System Information (please complete the following information):**
 - Server OS: N/A
 - Client OS: MacOS latest
 - Xpra Server Version N/A
 - Xpra Client Version : 4.4.3 (latest)

**Additional context**
Same when using the GUI and clicking on CONNECT.

**Comment by totaam** [comment] 2023-01-07 08:58
Looks like an exact duplicate of #3701 which is odd since you are installing via `brew`.
Also note that `brew` is not a supported installation method.

**Closed by totaam** 2023-01-07 08:58 UTC
Labels: bug
