### ISSUE TITLE
problems with virt-manager, QEMU extended key events

### ISSUE THREAD

**Issue by hfp-ak** [Xpra-org/xpra#3294] opened 2021-10-04 14:19 UTC
xpra 4.2.2 is working quite well with most programs here. However, with virt-manager there are 2 problems:

- on German keyboards Alt Gr is not working, so you cannot enter chars like {}[]\@. Some discussions claim that there is a link to QEMU extended key events not being supported. Other remote solutions are discussing the topic or have implementations, see: https://github.com/novnc/noVNC/commit/f4f4e8993d6daeb43b957766cd6973993232ba13 https://issues.apache.org/jira/browse/GUACAMOLE-609
- the Windows client often closes completely, the only hint in the log is "UI thread is now blocked" as a last line

**Comment by totaam** [comment] 2021-10-04 15:25
FYI: 4.2.3 was released today.
As per https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs , please specify your exact distro version.

QEMU's "extended key events" are an RFB (aka VNC) extension, so this is a non-starter for xpra, which is not RFB based at all, and adding vendor specific extensions to xpra's RFB backend is a very low priority.

I'll try testing `AltGr` with ` de` keyboard again, but if the problem is only with QEMU then it's likely that the bug needs to be fixed in QEMU.

As for the windows client closing, can you run it with `-d all` and post the last few hundred lines of output?
Is there anything specific that triggers this problem? A specific application perhaps?

**Comment by hfp-ak** [comment] 2021-10-04 15:36
I am using Gentoo (rolling release model, forward porting of this ebuild: https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-wm/xpra/xpra-4.2.1.ebuild).
Keyboard (AltGr) on virt-manager/qemu works perfectly if I just redirect the DISPLAY to a standard X11 xorg server.

**Comment by hfp-ak** [comment] 2021-10-04 16:40
one more hint for the keyboard issue: TigerVNC had the same problem that was fixed by the following patch:
https://github.com/TigerVNC/tigervnc/commit/0255e1b004fe6518c650e9d12b8862c2b2dad30b

**Comment by hfp-ak** [comment] 2021-10-05 11:38
[xpra-bug.zip](https://github.com/Xpra-org/xpra/files/7285469/xpra-bug.zip)
As requested: log with "-d all". The unexpected closing occurs in virt-manager (a GTK3 app written in Python). QEMU not running.

**Comment by totaam** [comment] 2021-10-05 12:03
@hfp-ak there is nothing in that log that looks suspicious, though I did find an unrelated bug!
You have opengl acceleration enabled, have you tried turning it off to see if that helps?
If so, please post the output of `xpra_cmd exe opengl` so we can blacklist that driver or card.

**Comment by hfp-ak** [comment] 2021-10-06 13:17
While it is still a bit early, it is becoming apparent that it does indeed have to do with opengl. No unexpected closes since now with opengl disabled. But I would not blacklist anything unless it is clear that it is not a bug in xpra and/or opengl python libs

GLU.version=1.2.2.0 Microsoft Corporation
accelerate=3.1.5
display_mode=DOUBLE
max-viewport-dims=32768, 32768
opengl=4.6
pyopengl=3.1.5
renderer=GeForce GT 1030/PCIe/SSE2
safe=True
shading-language-version=4.60 NVIDIA
success=True
texture-size-limit=32768
transparency=True
vendor=NVIDIA Corporation
zerocopy=True

**Closed** 2022-04-03 15:07 UTC
Labels: bug, client, keyboard
