### ISSUE TITLE
remote clipboard request timed out

### ISSUE THREAD

**Issue by fpoto** [Xpra-org/xpra#3661] opened 2022-10-20 20:29 UTC
I use a remote Emacs with both client and server at 4.4, both on Debian bookworm. Client is patched for the focus bug.

Very often copy and paste between client and a local window does not work. Since I call Xpra form the command line, I see this:
```
022-10-20 21:58:11,848 Warning: remote clipboard request timed out
2022-10-20 21:58:11,849  request id 1, selection=CLIPBOARD, target=UTF8_STRING
2022-10-20 21:58:14,358 Warning: remote clipboard request timed out
2022-10-20 21:58:14,358  request id 3, selection=CLIPBOARD, target=UTF8_STRING
2022-10-20 21:58:16,652 client ['Pluma', 'xid=6400028', 'pid=3496772'] is requesting an unknown target: 'GTK_TEXT_BUFFER_CONTENTS'
2022-10-20 21:58:16,653  using 'UTF8_STRING' instead
2022-10-20 21:58:16,871 Warning: remote clipboard request timed out
2022-10-20 21:58:16,871  request id 4, selection=CLIPBOARD, target=COMPOUND_TEXT
2022-10-20 21:58:18,278 client ['Pluma', 'xid=6400090', 'pid=3496772'] is requesting an unknown target: 'GTK_TEXT_BUFFER_CONTENTS'
2022-10-20 21:58:18,278  using 'UTF8_STRING' instead
2022-10-20 21:58:19,159 Warning: remote clipboard request timed out
2022-10-20 21:58:19,160  request id 5, selection=CLIPBOARD, target=UTF8_STRING
2022-10-20 21:58:19,425 Warning: remote clipboard request timed out
2022-10-20 21:58:19,426  request id 6, selection=CLIPBOARD, target=STRING
```

Does not happen with 4.3 client

**Comment by totaam** [comment] 2022-10-21 03:21
Very likely to be a duplicate of #3636, please re-open if not.

**Closed by totaam** 2022-10-21 03:21 UTC
Labels: bug
