### ISSUE TITLE
5.0.8MacOS Client has no Menu, Keyboard not working 

### ISSUE THREAD

**Issue by mainkats** [Xpra-org/xpra#4357] opened 2024-09-13 17:16 UTC
**Describe the bug**
When starting Xpra on an arm64 Mac and attaching to a remote server, the connection establishes and the Windows are drawn, but:
  - Keyboard is not working
  - Xpra Client Menus are empty, and hotkeys are not working 
Mouse for the remote windows is working, though.

**To Reproduce**
1. server command: xpra start :XX 
2. client command:
/Applications/Xpra5.0.10.app/Contents/MacOS/Xpra attach --ssh=ssh --microphone=off --speaker=off ssh://username@server/XX
3. specific action to trigger the bug: Triggers on connection

**System Information (please complete the following information):**
 - Server OS: Debian bookworm
 - Client OS: OSX 13.6.9
 - Xpra Server Version 6.1.2-r1-1
 - Xpra Client Version 5.0.10-r8

**Additional context**
The same error happens with 5.0.9, connection works with the 5.0.8 Release.

In the console, this Python error pops up:
```
2024-09-13 19:09:47,142 Xpra GTK3 client version 5.0.10-r0
2024-09-13 19:09:47,156  running on Mac OS X 13.6.9
xpra main error:
Traceback (most recent call last):
  File "/Applications/Xpra5.0.10.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 121, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Xpra5.0.10.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 455, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Xpra5.0.10.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 642, in do_run_mode
    return run_splash(args)
           ^^^^^^^^^^^^^^^^
  File "/Applications/Xpra5.0.10.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 2402, in run_splash
    return splash_screen.main(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Xpra5.0.10.app/Contents/Resources/lib/python/xpra/splash_screen.py", line 294, in main
    with program_context("splash", "Splash"):
  File "/Applications/Xpra5.0.10.app/Contents/Resources/lib/python/xpra/platform/__init__.py", line 79, in __enter__
    init(self.prgname, self.appname)
  File "/Applications/Xpra5.0.10.app/Contents/Resources/lib/python/xpra/platform/__init__.py", line 24, in init
    do_init()
  File "/Applications/Xpra5.0.10.app/Contents/Resources/lib/python/xpra/platform/darwin/__init__.py", line 15, in do_init
    from AppKit import NSApp    #@UnresolvedImport
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "AppKit/__init__.pyc", line 217, in <module>
  File "AppKit/__init__.pyc", line 12, in _setup
  File "Foundation/__init__.pyc", line 203, in <module>
  File "Foundation/__init__.pyc", line 12, in _setup
  File "CoreFoundation/__init__.pyc", line 37, in <module>
  File "CoreFoundation/__init__.pyc", line 12, in _setup
  File "objc/__init__.pyc", line 7, in <module>
  File "objc/_objc.pyc", line 13, in <module>
  File "objc/_objc.pyc", line 9, in __load
  File "imp.pyc", line 343, in load_dynamic
ImportError: dlopen(/Applications/Xpra5.0.10.app/Contents/Resources/lib/python/lib-dynload/objc/_objc.so, 0x0002): symbol not found in flat namespace '_ffi_find_closure_for_code_np'
```

**Comment by totaam** [comment] 2024-09-14 16:44
I believe this is a duplicate of https://github.com/Xpra-org/gtk-osx-build/issues/27

TBH, I don't think any of us understand why this occasionally breaks, or how to fix it once and for all.
The only thing I could do is to spin a full rebuild of the whole ~135 packages that make up the environment we use for building xpra.
Does 5.0.10-r1 work any better?

**Comment by mainkats** [comment] 2024-09-18 03:50
> Does 5.0.10-r1 work any better?

Yes, with 5.0.10-r1 the keyboard works and the menu shows up.

**Comment by totaam** [comment] 2024-09-18 08:26
I have also issued `6.1.2-r1` from the same build environment.

This will do for now, until it breaks again..

**Closed by totaam** 2024-09-18 08:26 UTC
Labels: bug
