### ISSUE TITLE
xpra fails on launch, python exception

### ISSUE THREAD

**Issue by colingoodman** [Xpra-org/xpra#4081] opened 2023-12-18 17:22 UTC
**Describe the bug**
On a Mac fresh installation of the latest version of xpra, I receive the following:
`zsh: command not found: xpra`
Starting the application via the apps folder, the xpra icon appears in the dock momentarily before disappearing.

If I try to launch xpra via the file in  `/usr/local/bin` I get a python exception:

```
grep: /usr/share/locale/locale.alias: No such file or directory
xpra main error:
Traceback (most recent call last):
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 121, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 455, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 599, in do_run_mode
    return gui.main(cmdline)
           ^^^^^^^^^^^^^^^^^
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/gtk_common/gui.py", line 263, in main
    from xpra.platform.darwin.gui import wait_for_open_handlers
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/platform/darwin/gui.py", line 15, in <module>
    import objc                         #@UnresolvedImport
    ^^^^^^^^^^^
  File "objc/__init__.pyc", line 6, in <module>
  File "objc/_objc.pyc", line 14, in <module>
  File "objc/_objc.pyc", line 10, in __load
  File "imp.pyc", line 343, in load_dynamic
ImportError: dlopen(/Applications/Xpra.app/Contents/Resources/lib/python/lib-dynload/objc/_objc.so, 0x0002): symbol not found in flat namespace '_ffi_find_closure_for_code_np'
```

**To Reproduce**
1. Install xpra
2. Try to launch via apps
3. Type `xpra` into the terminal, see command not found
4. Type `/usr/local/bin/xpra` into the terminal, receive exception

**System Information (please complete the following information):**
 - Server OS: N/A
 - Client OS: Mac Sonoma 14.1.1
 - Xpra Server Version N/A
 - Xpra Client Version, [latest stable version from the git page](https://github.com/Xpra-org/xpra)

(Did not include server information as this is solely a client problem)
 
**Additional context**
I have reinstalled Xpra using both the pkg file on the Github page as well as homebrew. Both lead to the same result as described above.

Thanks in advance for any help / support.

**Comment by totaam** [comment] 2023-12-25 14:58
This looks like yet another duplicate of https://github.com/Xpra-org/gtk-osx-build/issues/27

**Closed** 2023-12-29 13:47 UTC
Labels: bug
