### ISSUE TITLE
Grab keyboard in shadow situations

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3388] opened 2021-12-16 10:25 UTC
**Is your feature request related to a problem? Please describe.**
When both window managers are set to Alt+Tab for switching windows, it is impossible (at least in Windows [client] --> Ubuntu [server]) to Alt+Tab switch windows

**Describe the solution you'd like**
There could be an explicit button (and/or shortcut /w visual aid) that grabs everything that it can (except e.g. Ctrl+Alt+Del in Windows that's un-grabable) and directs it through Xpra to the server.

You could also use mouse as intention - click inside the window and all input is grabbed, click outside and the OS is able to first interpret the input, then Xpra gets it to direct it.

It's a commonplace solution that you've probably seen in VMs (and Teamviewer in Ubuntu as client shows pretty nice; you should test the interaction if you haven't)

**Describe alternatives you've considered**
No alternatives - you have to "go manual" and forgo of some shortcuts.

**Additional context**

**Comment by totaam** [comment] 2022-04-26 15:19
Duplicate of #3059

**Closed by totaam** 2022-04-26 15:19 UTC
Labels: enhancement, client, keyboard
