### ISSUE TITLE
xpra fails to start using ssh on macOS Ventura

### ISSUE THREAD

**Issue by keisisqrl** [Xpra-org/xpra#3757] opened 2023-02-03 21:29 UTC
When trying to start on macOS Ventura, xpra crashes with this output:

```
2023-02-03 13:20:21,905 Xpra GTK3 client version 4.4.3-r1 64-bit
2023-02-03 13:20:21,951  running on Mac OS X 10.16
xpra main error:
Traceback (most recent call last):
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 142, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 451, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 495, in do_run_mode
    return run_client(script_file, cmdline, error_cb, options, args, mode)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 1236, in run_client
    app = get_client_app(script_file, cmdline, error_cb, opts, extra_args, mode)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 1401, in get_client_app
    app = get_client_gui_app(error_cb, opts, request_mode, extra_args, mode)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 1437, in get_client_gui_app
    app.init(opts)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/client/gtk_base/gtk_client_base.py", line 131, in init
    UIXpraClient.init(self, opts)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/client/ui_client_base.py", line 177, in init
    c.init(self, opts)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/client/mixins/network_listener.py", line 50, in init
    self.sockets = create_sockets(opts, err)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/net/socket_util.py", line 320, in create_sockets
    import paramiko
  File "paramiko/__init__.pyc", line 22, in <module>
  File "paramiko/transport.pyc", line 132, in <module>
  File "paramiko/transport.pyc", line 206, in Transport
  File "paramiko/kex_curve25519.pyc", line 30, in is_available
  File "cryptography/hazmat/primitives/asymmetric/x25519.pyc", line 39, in generate
  File "cryptography/hazmat/backends/openssl/__init__.pyc", line 6, in <module>
  File "cryptography/hazmat/backends/openssl/backend.pyc", line 63, in <module>
  File "cryptography/hazmat/bindings/openssl/binding.pyc", line 228, in <module>
  File "cryptography/hazmat/bindings/openssl/binding.pyc", line 188, in init_static_locks
  File "cryptography/hazmat/bindings/openssl/binding.pyc", line 176, in _ensure_ffi_initialized
  File "cryptography/hazmat/bindings/openssl/binding.pyc", line 90, in _openssl_assert
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=126353445, lib=15, reason=524325, reason_text=b'error:07880025:common libcrypto routines::reason(524325)')])
```

**Comment by totaam** [comment] 2023-02-04 08:31
Duplicate of #3701

Use: `--ssh=ssh --ssh-upgrade=no`.

**Closed by totaam** 2023-02-04 08:31 UTC
