### ISSUE TITLE
TypeError: object of type 'int' has no len() in gl_window_backing_base

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#3971] opened 2023-08-22 21:37 UTC
**Describe the bug**

**To Reproduce**
1. xpra start
2. xpra connect
3. ?

**System Information (please complete the following information):**
 - Server OS: Debian Bookworm
 - Client OS: Debian Trixie
 - Xpra Server Version xpra 5.0-r0-1
 - Xpra Client Version 5.0-r32900-1

**Additional context**
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/client/base/client_base.py", line 1237, in call_handler
    handler(packet)
  File "/usr/lib/python3/dist-packages/xpra/client/mixins/window_manager.py", line 589, in _process_cursor
    self.set_windows_cursor(self._id_to_window.values(), new_cursor)
  File "/usr/lib/python3/dist-packages/xpra/client/gtk3/gtk_client_base.py", line 953, in set_windows_cursor
    w.set_cursor_data(cursor_data)
  File "/usr/lib/python3/dist-packages/xpra/client/gtk3/gtk_client_window_base.py", line 798, in set_cursor_data
    self.when_realized("cursor", b.set_cursor_data, cursor_data)
  File "/usr/lib/python3/dist-packages/xpra/client/gtk3/gtk_client_window_base.py", line 900, in when_realized
    callback(*args)
  File "/usr/lib/python3/dist-packages/xpra/client/gl/gl_window_backing_base.py", line 1007, in set_cursor_data
    if not self.validate_cursor():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/client/gl/gl_window_backing_base.py", line 989, in validate_cursor
    if len(pixels)!=blen:
TypeError: object of type 'int' has no len()
```

**Comment by totaam** [comment] 2023-08-23 02:21
Dupe of #3959

**Closed by totaam** 2023-08-23 02:21 UTC
Labels: bug, duplicate, invalid
