### ISSUE TITLE
Possibility to automatic grab input (keyboard and/or mouse) when client window get focus

### ISSUE THREAD

**Issue by tonich-sh** [Xpra-org/xpra#3059] opened 2021-03-19 10:28 UTC
Like in VirtualBox with guest additions installed

**Comment by totaam** [comment] 2021-03-19 12:52
I don't understand what this is meant to do in xpra. (and I do use virtualbox)
Keyboard events should already go to the window that has focus, and pointer events too - as long as there are valid events to forward, that is: movements within that window.

**Comment by tonich-sh** [comment] 2021-03-22 10:13
If i use start-desktop mode i have full desktop environment (DE) in xpra window. This DE has own key bindings, which is may intersecting with local DE key bindings (for example switching between virtual desktops). Currently when i'm focusing xpra window i need manually toggle grab keyboard to be able switching desktops in remote DE. The same for mouse: i'm using tile WM without window decoration and perform moving and resizing window by pressing some 'mod' key and drag window by mouse. Without full input grabbing this action resizes xpra window (i'm using the same DE in remote and local with same bindings) instead of window in remote DE.

**Comment by totaam** [comment] 2021-03-22 17:10
> .. i need manually toggle grab keyboard to be able switching desktops in remote DE

Gotcha. I thought it would be easy (similar to #1195), so I started preparing the codebase (couple of commits above).
But the problem is that GTK is not forwarding any of the focus events to the window whilst we own the grab, and so we can't release it when we should. Without the grab:
```
2021-03-22 23:00:29,578 focus-out-event for wid=1
2021-03-22 23:00:29,578 do_xpra_focus_out_event(<Gdk.EventFocus object at 0x7fdce9578450 (void at 0x562296ebeab0)>)
2021-03-22 23:00:29,579 ClientWindow(1) focus_change(ClientWindow(1), <GParamBoolean 'has-toplevel-focus'>) has-toplevel-focus=False, _been_mapped=True
2021-03-22 23:00:29,580 recheck_focus() wid=1, focused=1, latest=False
2021-03-22 23:00:29,580 keyboard_ungrab()
2021-03-22 23:00:29,581 window_ungrab()
2021-03-22 23:00:29,582 _unfocus() wid=1, focused=1
2021-03-22 23:00:29,583 update_focus(1, False) focused=1, grabbed=None
```
With the grab, we get nothing!

Here's what I was testing with:
```
diff --git a/xpra/client/gtk_base/gtk_client_window_base.py b/xpra/client/gtk_base/gtk_client_window_base.py
index 3bbee582b..1cfabfd34 100644
--- a/xpra/client/gtk_base/gtk_client_window_base.py
+++ b/xpra/client/gtk_base/gtk_client_window_base.py
@@ -472,9 +472,11 @@ class GTKClientWindowBase(ClientWindowBase, Gtk.Window):
             self._unfocus()
 
     def _focus(self):
+        self.keyboard_grab()
         super()._focus()
 
     def _unfocus(self):
+        self.keyboard_ungrab()
         self._client.window_ungrab()
         super()._unfocus()
 
```

What's strange is that we do have code to workaround this (`do_init_focus`), the docstring even says:
*hook up the X11 gdk event notifications so we can get focus-out when grabs are active*
Maybe this no longer works with GTK3? And this probably will not work with Wayland either.
So I'm going to have to leave this as it is for now.

**Comment by totaam** [comment] 2021-07-13 15:15
See also #3118

**Comment by totaam** [comment] 2022-07-02 08:32
According to [Gtk 4 - grab keyboard](https://discourse.gnome.org/t/gtk-4-grab-keyboard/6251): `gdk_seat_grab(default_seat, window, GDK_SEAT_CAPABILITY_KEYBOARD, …)` should work with GTK3.
That's [Gdk.Seat.grab](https://lazka.github.io/pgi-docs/Gdk-3.0/classes/Seat.html#Gdk.Seat.grab) with gi introspection.

**Comment by stdedos** [comment] 2022-07-02 16:34
So, that means ... it should work, or it needs work to be done?

**Comment by totaam** [comment] 2022-07-05 08:07
> So, that means ... it should work, or it needs work to be done?

It needs work.
I'm pretty sure I had tried every conceivable API call (including the ones that end up calling `Seat.grab`), but I will try again.

**Comment by totaam** [comment] 2022-07-05 08:08
> So, that means ... it should work, or it needs work to be done?

It needs work.
I'm pretty sure I had tried every conceivable API call (including the ones that end up calling `Seat.grab`), but I will try again.

**Comment by totaam** [comment] 2022-07-05 19:55
Well I have tried this new variation of the same API and got the exact same result as before: nothing happens and shortcuts like Alt-Tab cannot be intercepted.

**Comment by stdedos** [comment] 2022-07-05 20:01
_C'est la vie then 😕_ 😞

**Comment by totaam** [comment] 2022-07-06 18:17
The commit above implements this `autograb` feature. The default setting is:
https://github.com/Xpra-org/xpra/blob/8fde7c522d885ce43ed75cc47db7cfb97dcfd978/xpra/client/gtk_base/gtk_client_window_base.py#L125

This should probably also have a tray menu entry?
I haven't tested MS Windows or MacOS clients, we'll see if this laptop can run the build virtual machines without setting it on fire.
I'll also have to check under X11 since this prompt seems to come from the wayland based DE.

**Comment by totaam** [comment] 2022-07-12 13:37
> Meaning keyboard autograb, right? And as soon as the mouse is "out", then keyboard is released?

I didn't at the time, but the 2 commits above corrected that.

One thing that I would still like to be able to do is optional pointer confinement so that when running a full remote desktop, one could more easily trap the pointer within that window(s) - ala-virtualbox.
I've tried the same grab API, but that didn't work, again. Perhaps I am doing it wrong, again?

**Comment by stdedos** [comment] 2022-07-18 20:38
Now doing `Alt+Tab` while focusing the shadow monitor window "does nothing":

Windows has lost the shortcut (yay!), but the shadowed server "_does not receive it_" (or rather, does not seem to do anything about it)

_If needed: For the rest of the details, see the archive: [shadow-0.tbz.zip](https://github.com/Xpra-org/xpra/files/9135582/shadow-0.tbz.zip) (_it's not a zip file! but Github is special ..._)_

**Comment by totaam** [comment] 2022-08-22 10:54
@stdedos as of ad213574a8093305a363feb26641439b75fd3019, you can now also toggle pointer confinement on MS Windows using the shortcut `Control+F9`.
Unlike keyboard grabs, I don't think that we should make this semi-automatic for any session types.

> Now doing `Alt+Tab` while focusing the shadow monitor window "does nothing":

I have been testing with desktop sessions only until now, it's possible that the key translation used by shadow servers somehow fails to trigger the correct key events and the window manager doesn't see `Alt+Tab` but something else. (if so then it would be a different keyboard bug)

**Comment by totaam** [comment] 2022-08-22 11:49
Bypassing GTK to call [XGrabPointer](https://tronche.com/gui/x/xlib/input/XGrabPointer.html) directly makes this work for X11 clients.

@stdedos can we close this ticket?

---

Which only leaves (for different tickets):
* wayland clients: an **unstable** protocol exists: [pointer-constraints-unstable-v1](https://wayland.app/protocols/pointer-constraints-unstable-v1) but there is no support for this in GTK -   amusingly, using this API can crash the wayland compositor [Wayland pointer-constraints-unstable-v1 crashes mutter](https://gitlab.gnome.org/GNOME/mutter/-/issues/425) and since this isn't X11 where the window manager is a separate process you can restart or replace, you will not just lose your window manager but your whole desktop session! (but _more secure_, or something)
* MacOS does not have an API for this feature!

**Closed** 2022-09-02 10:20 UTC
Labels: enhancement, keyboard

**Comment by stdedos** [comment] 2023-09-10 20:13
Everything seems to work perfectly

... except `Alt+Tab` 😕 

![image](https://github.com/Xpra-org/xpra/assets/133706/e32ecaf8-cdaf-46bd-ad63-1c5500a39e50)

At least, in grabbed mode, `WinKey+Tab` works, and `Alt+Tab` is not grabbed by Win10

**Comment by stdedos** [comment] 2023-09-10 20:25
... It's so good, I can switch to different ttys 😅 

(and then the shadow window goes totally transparent 😓)
