### ISSUE TITLE
tcl/tk applications' menus appear at random places on the screen outside of the application window

### ISSUE THREAD

**Issue by djerius** [Xpra-org/xpra#3801] opened 2023-03-20 20:14 UTC
**Describe the bug**
On applications which use tcl/tk, selecting an application menu with the cursor results in the menu appearing somewhat randomly outside of the main application window. Passing the cursor over any other menu on the application causes the "floating" menu to change to that menu.  Sub menus also exhibit this behavior.  

An example application can be found here:
https://sites.google.com/cfa.harvard.edu/saoimageds9/home

**To Reproduce**
1. On client: xpra start ssh://server --start=ds9
2. click on an application menu

**System Information (please complete the following information):**
 - Server OS: Debian 10
 - Client OS: Debian 11
 - Xpra Server Version: v4.4.4-r0
 - Xpra Client Version: v4.4.4-r0

**Additional context**
I've attached a screencast showing the behavior.

[xpra-ds9.webm](https://user-images.githubusercontent.com/196875/226454579-67c6bd98-97fc-4367-b6bd-b58a1424862a.webm)

**Comment by totaam** [comment] 2023-03-21 05:53
Is this a wayland desktop? If so, does it work better if you run with Xorg instead?
Do you have a bare bones tcl/tk application I can test with? Like an example hello-world type of app?

**Comment by totaam** [comment] 2023-03-21 15:47
> Much better! The menus appear where they should,

That's a Wayland "feature": they decided that applications should not place windows where they want and that only the compositor knows best.
Hopefully there is a kludge we can use to force it.

**Comment by djerius** [comment] 2023-03-21 15:55
> That's a Wayland "feature": they decided that applications should not place windows where they want and that only the compositor knows best.

That's unfortunate. 

Maybe I'll try running this in a local X11 xvfb and connect to that. 

(I've pursued the alternative of running a full remote desktop, but I've run into issues starting new sessions after the first successful one, but haven't had time to put together a proper bug report on that.  Anyway, that's for another bug report.)

**Comment by totaam** [comment] 2023-06-07 15:34
> I've run into issues starting new sessions after the first successful one, but haven't had time to put together a proper bug report on that

If you're using the same user account, then this can happen as more applications now tend to run as "singletons".
If full desktop sessions are interfering with each other (ie: stopping one impacts others) then this is just a Debian bug and you should switch to a better distro.

**Comment by djerius** [comment] 2023-06-07 17:20
> If you're using the same user account, then this can happen as more applications now tend to run as "singletons".
> If full desktop sessions are interfering with each other (ie: stopping one impacts others) then this is just a Debian bug and you should switch to a better distro.

For work reasons the remote box is running Debian 10 (ancient).  I'll revisit the issue with sessions when the box is upgraded to Debian 12, which is forthcoming.

**Comment by totaam** [comment] 2023-07-11 19:22
I can reproduce the problem with this test app:
```python
#!/usr/bin/python3

from tkinter import *
from tkinter import messagebox


class MyWindow(Tk):

    def __init__(self):
        Tk.__init__(self)
        self.create_menu_bar()
        self.geometry("300x200")
        self.title("Test Menu Bar")

    def create_menu_bar(self):
        menu_bar = Menu(self)

        menu_file = Menu(menu_bar, tearoff=0)
        menu_file.add_command(label="New", command=self.do_something)
        menu_file.add_command(label="Open", command=self.open_file)
        menu_file.add_command(label="Save", command=self.do_something)
        menu_file.add_separator()
        menu_file.add_command(label="Exit", command=self.quit)
        menu_bar.add_cascade(label="File", menu=menu_file)

        menu_edit = Menu(menu_bar, tearoff=0)
        menu_edit.add_command(label="Undo", command=self.do_something)
        menu_edit.add_separator()
        menu_edit.add_command(label="Copy", command=self.do_something)
        menu_edit.add_command(label="Cut", command=self.do_something)
        menu_edit.add_command(label="Paste", command=self.do_something)
        menu_bar.add_cascade(label="Edit", menu=menu_edit)

        menu_help = Menu(menu_bar, tearoff=0)
        menu_help.add_command(label="About", command=self.do_about)
        menu_bar.add_cascade(label="Help", menu=menu_help)

        self.config(menu=menu_bar)

    def open_file(self):
        from tkinter.filedialog import askopenfilename
        file = askopenfilename(title="Choose the file to open",
                               filetypes=[("PNG image", ".png"), ("GIF image", ".gif"), ("All files", ".*")])
        print(file)

    def do_something(self):
        print("Menu clicked")

    def do_about(self):
        messagebox.showinfo("My title", "My message")


window = MyWindow()
window.mainloop()
```

**Comment by totaam** [comment] 2023-07-11 19:53
Here's the metadata for the OR menu window created from the example window code above when shown at: `windows.10.geometry=(26, 60, 300, 234)`:
```
Discovered new override-redirect window: 0xc00022 X11 geometry=(63, 93, 58, 117, 0, 24)
_NET_WM_NAME=#!menu#!menu2
WM_PROTOCOLS=['WM_DELETE_WINDOW']
WM_CLASS=('#!menu#!menu2', 'Menu')
WM_TRANSIENT_FOR=None
_NET_WM_WINDOW_TYPE=['_NET_WM_WINDOW_TYPE_POPUP_MENU']
getWMHints(0xc00022)={'input': 1, 'initial_state': 1}
```
So `tkinter` is just requesting a position that isn't anywhere near the menu button.

The client does spew out this warning:
```
Gdk-Message: 21:43:17.985: Window 0x559fb3849f20 is a temporary window without parent, application will not be able to position it on screen.

(Xpra:297465): Gdk-WARNING **: 21:43:17.985: Couldn't map as window 0x559fb3849f20 as popup because it doesn't have a parent
```

> although once I managed to get the application to move behind another window while the menu stayed above it

It seems that `tkinter` creates all the menu OR windows as children of the root window... so problems like these are bound to happen.

**Comment by totaam** [comment] 2023-07-11 20:59
And... that's because GTK3 on Wayland lies about the window's position and always returns `26,23`!
So `tkinter` then places the OR window relative to that... which is nowhere near the actual position of the window.

This works through Xwayland because the Wayland compositors honour the window position requests when coming from that specific application. But they snub every other app, including xpra.

I don't think this can be fixed without some major kludges: we could special case TK override-redirect popup menu windows and make them relative to their parent, but since TK doesn't expose any relationship between the popup and its parent.. again, we would have to guess.

It might be easier to submit a patch to TK to set the `transient-for` attribute on popup windows, as they should be doing.

**Closed by totaam** 2023-07-11 20:59 UTC
Labels: bug, client, geometry
