### ISSUE TITLE
OpenGL Error on windows 11 in v6.0 client

### ISSUE THREAD

**Issue by alexisshaw** [Xpra-org/xpra#4238] opened 2024-05-23 00:46 UTC
When connecting to the server on v6.0 I recieve an error message saying opengl could not attach.
**To Reproduce**
1. server command
xpra start :10
2. client command
open connect over ssh specifically username@server:22/10 from gui
3. specific action to trigger the bug
Pressing the connect button causes glitch, scroll tearing shows even in the terminal app, but is especially prevalent in the client application I am using which is cadence virtuoso.

Rolling back to v 5.0.8 on the client solved the issue for me for now.

the error shown is the same as in this comment from issue #4205 https://github.com/Xpra-org/xpra/issues/4205#issuecomment-2087209136

My laptop is a dell precision 5680 with a i7-13800H and the active GPU is a RTX4000 Ada generation Laptop GPU. the problem exists with the laptop screen off, and only a single main monitor at 100% scaling. Driver version 31.0.15.3827.

**System Information (please complete the following information):**
 - Server OS: RHEL 8.0
 - Client OS: Windows 11
 - Xpra Server Version 6.0
 - Xpra Client Version 6.0

**Comment by totaam** [comment] 2024-05-23 03:37
> scroll tearing shows even in the terminal app

I believe this is tracked in #4201

> open connect over ssh specifically username@server:22/10 from gui

Does this also occur if using the command line?
ie:
`xpra_cmd.exe attach ssh://username@server:22/10`

**Comment by alexisshaw** [comment] 2024-05-23 03:50
Yes. I tried that first, and the tearing still happens, though the error pop up doesn't

**Comment by totaam** [comment] 2024-05-23 03:55
> Yes. I tried that first, and the tearing still happens,

The tearing is a duplicate of #4201.

> though the error pop up doesn't

I have no idea what's causing that one, works fine here.

**Comment by totaam** [comment] 2024-05-23 04:35
> an error message saying opengl could not attach

Please include the exact error message, I'm pretty sure there is already a ticket for this issue - but I cannot locate it without the message.

**Comment by alexisshaw** [comment] 2024-05-23 05:12
I linked to it, and It is the ticket linked it was exactly the same as the image in the link, but it is trans8ent so getting a pic of it is frustrating.

All the Best
Alexis
________________________________

**Comment by totaam** [comment] 2024-05-23 05:47
Sorry, I had missed it.
I'm closing this ticket since it is a duplicate of #4205 - feel free to subscribe there.

**Closed by totaam** 2024-05-23 05:47 UTC
Labels: bug
