### ISSUE TITLE
Jetbrains' "Search Everywhere" window ends up stale/unrendered

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3105] opened 2021-04-30 09:22 UTC
_There must be another issue like that somewhere, but I cannot find it_

"Search Everywhere" window ends up stale/unrendered partially.

![xpra-2021-04-16_11-40-39](https://user-images.githubusercontent.com/133706/116674820-cab18500-a9ad-11eb-89de-e8d60cd19726.png)

The window appears to be rendered only "the very first instance" it appears, and when it becomes the size it will be etc, it seems that only the "new extra part" will continue being rendered.

The purple background (and the two lines above it) are accurate representations of how rendering looks like. Purple is the `gnome-terminal` background, which happened to be empty; however, even a video from another app (e.g. a browser on the client outside xpra) will be shown there - it is as if there is no window where the purple box is, and as if the two lines above the purple box are frozen.

"Nominal setup": S:Focal/C:Win10, xpra v4.1.x both, 2 monitors on client.

**Comment by totaam** [comment] 2021-05-17 17:38
I cannot reproduce with the current versions.
Is this still a problem?

**Comment by stdedos** [comment] 2021-05-17 17:59
Yeah (100% reproducibility on my setup), but I haven't updated to your latest package (_I have downloaded them_, but I haven't `xpra upgrade` the server - I don't to yet-again re-assign windows to monitors).

I can try that tomorrow if you wish / think you've fixed that in some other issue.

**Comment by stdedos** [comment] 2021-05-19 06:36
Now it's a bit worse: The weird rendering (the left side) always reflects init state of the previous rendering.
Because on the first time the "previous time rendering" was nada, it renders the gray portion as white.
(and after that with whatever the window contents were last time)

**Comment by totaam** [comment] 2021-05-19 11:30
> The weird rendering (the left side) always reflects init state of the previous rendering.

Does forcing a refresh from the tray menu help?

***

Here's what I've tried:
* Ubuntu Bionic server, xpra 4.1.3
* Windows 10 client VirtualBox VM (so opengl is off), xpra 4.2 latest
* `xpra attach` (tcp / ssh whatever)
* install jetbrains toolbox
* install pycharm community edition from there
* run pycharm, hit `Shift` twice

Everything looks as it should.
What am I missing?

**Comment by stdedos** [comment] 2021-05-19 11:32
Dual monitors? 😕

**Comment by totaam** [comment] 2021-05-19 12:59
> Dual monitors?

Nope. Just tried it.

**Comment by stdedos** [comment] 2021-05-20 07:39
It's impossible to use the tray, because that window is closed on window loosing focus.

However, what thickens the plot is that **only my main working project** exhibits that error.
If I start a new (empty) project, the window appears "as expected": Centered on one screen, properly sized, and rendered almost perfectly (there is some flickering white in place of 100% transparency, but it's only a flickering).

And Jetbrains will never accept to troubleshoot such error 😩

**Comment by totaam** [comment] 2021-05-20 07:46
> It's impossible to use the tray, because that window is closed on window loosing focus.

You could use the magic key combination with `F1` to bring up the menu anywhere over that window. (IIRC that's `Ctrl` + `Shift` + `F1` on Linux)
Or you could create a new shortcut that calls `refresh_window` or `refresh_all_windows`.
ie: `--key-shortcut=#+R=refresh_all_windows`

Since this requires a very specific set of circumstances using a closed-source application, I am going to close this ticket.

**Closed by totaam** 2021-05-20 07:46 UTC
Labels: bug, geometry, question

**Comment by stdedos** [comment] 2021-05-20 08:17
> `--key-shortcut=#+R=refresh_all_windows`

Typo: `--key-shortcut=#+R:refresh_all_windows`

**Comment by totaam** [comment] 2021-05-20 11:10
> Typo

As per the commit above. No longer a typo!
Nicer too as it allows `:` and `=` to be used as keys:
`--key-shortcut=#+:=refresh_all_windows`
`--key-shortcut=#+=:refresh_window`
