### ISSUE TITLE
QUIC connection fails to start with "Idle timeout" from Windows to Ubuntu

### ISSUE THREAD

**Issue by jzyrobert** [Xpra-org/xpra#3850] opened 2023-05-11 15:28 UTC
**Describe the bug**
Trying to connect to an Xpra server over QUIC UDP is failing with `connection failed: Idle timeout`.
In the debug logs, the last lines before the error are:
```
CreatePipeHandle()=0x1f24
ConnectNamedPipe()=0
GetLastError()=Overlapped I/O operation is in progress. (997)
Traceback (most recent call last):
  File "E:/xpra/xpra/scripts/main.py", line 933, in connect_or_fail
  File "E:/xpra/xpra/scripts/main.py", line 1126, in connect_to
  File "E:/xpra/xpra/net/quic/client.py", line 226, in quic_connect
  File "E:/xpra/xpra/net/quic/asyncio_thread.py", line 100, in sync
Exception: Idle timeout
```
I've verified that the UDP connection should work by running `nc -ul 4000` on the server side and sending over data from the client.
I've also tested this over a wireguard VPN connection that is port-forwarding UDP 4000 and the logs show that it detects the test packets I send, but when Xpra is starting up no UDP packets are detected by wireguard.

**To Reproduce**
1. `xpra start --bind-quic=0.0.0.0:4000 --ssl-cert ssl-cert.pem --ssl-key key.pem --no-daemon --debug quic`
2. `.\Xpra_cmd.exe attach quic://IP_ADDRESS:4000/ --ssl-server-verify-mode=none --compress=0 --bandwidth-detection=no
 --speed=100 --debug quic --debug network`
3. Client cannot connect

**System Information (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Client OS: Windows 10
 - Xpra Server Version v5.0-r33336 (gd0fbf257e)
 - Xpra Client Version xpra v5.0-r33337 (ga7f97a3ad)

**Comment by jzyrobert** [comment] 2023-05-11 15:38
> @jzyrobert did you try to connect locally on the server? Even just `xpra info quic://127.0.0.1:4000/`?

Of the two servers I tried:
First one reports
```
no uvloop
Warning: failed to connect:
 connection failed: Idle timeout
```

Second reports
```
no uvloop
Exception in callback _SelectorDatagramTransport._read_ready()
handle: <Handle _SelectorDatagramTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/home/<user>/.local/lib/python3.10/site-packages/aioquic/asyncio/protocol.py", line 135, in datagram_received
    self._quic.receive_datagram(cast(bytes, data), addr, now=self._loop.time())
  File "/home/<user>/.local/lib/python3.10/site-packages/aioquic/quic/connection.py", line 992, in receive_datagram
    is_ack_eliciting, is_probing = self._payload_received(
  File "/home/<user>/.local/lib/python3.10/site-packages/aioquic/quic/connection.py", line 2286, in _payload_received
    frame_handler(context, frame_type, buf)
  File "/home/<user>/.local/lib/python3.10/site-packages/aioquic/quic/connection.py", line 1510, in _handle_crypto_frame
    self.tls.handle_message(event.data, self._crypto_buffers)
  File "/home/<user>/.local/lib/python3.10/site-packages/aioquic/tls.py", line 1254, in handle_message
    self._client_handle_certificate_verify(input_buf)
  File "/home/<user>/.local/lib/python3.10/site-packages/aioquic/tls.py", line 1519, in _client_handle_certificate_verify
    verify_certificate(
  File "/home/<user>/.local/lib/python3.10/site-packages/aioquic/tls.py", line 246, in verify_certificate
    store.load_locations(cafile, capath)
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1751, in load_locations
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('system library', '', ''), ('BIO routines', '', 'no such file'), ('x509 certificate routines', '', 'system lib')]
[5bc66bf29f7e464b] Duplicate CRYPTO data received for epoch Epoch.HANDSHAKE
```

Also I could not run `xpra info quic://127.0.0.1:4000/` as that gives `Warning: failed to connect:
 connection failed: hostname '127.0.0.1' doesn't match 'localhost'`
The above is when running with localhost:4000

**Comment by totaam** [comment] 2023-05-11 15:54
Your command lines probably need to specify the ssl certificates you are using with the server, as per https://github.com/Xpra-org/xpra/issues/3376#issuecomment-1310497008

You haven't specified how you installed `aioquic` or its dependencies which are not available in the Ubuntu repositories.

If you still have problems, please first try with a distribution that supports `aioquic` out of the box. The Fedora repositories on `xpra.org` should have everything needed and I should be able to reproduce issues easily enough.

**Comment by jzyrobert** [comment] 2023-05-11 16:18
> Your command lines probably need to specify the ssl certificates you are using with the server, as per [#3376 (comment)](https://github.com/Xpra-org/xpra/issues/3376#issuecomment-1310497008)
> 
> You haven't specified how you installed `aioquic` or its dependencies which are not available in the Ubuntu repositories.
> 
> If you still have problems, please first try with a distribution that supports `aioquic` out of the box. The Fedora repositories on `xpra.org` should have everything needed and I should be able to reproduce issues easily enough.

Passing `ssl-server-verify-mode=none` made `xpra info quic://127.0.0.1:4000/` work on both servers. I have already been passing it to the remote client commands.

I installed aioquic on the servers by using `sudo apt install libssl-dev python3-dev` and then `pip install aioquic`.
I suspect the error is on the windows side, as the debug logs on the server never show them receiving a connection.
Will try with a Fedora distribution if I can.

**Comment by totaam** [comment] 2023-05-11 16:33
@jzyrobert no need to try Fedora if the servers can connect to themselves.

**Comment by jzyrobert** [comment] 2023-05-11 17:47
> @jzyrobert no need to try Fedora if the servers can connect to themselves.
> 
> Please run xpra with `-d quic` added to its command line and set the environment variable `XPRA_IPV6=0`.

Thanks, setting that variable made the connection work. However it's very unstable and dies very quickly after connecting, with errors like
```2023-05-11 18:41:30,800 Error: read on XpraQuicConnection<0> failed: <class 'RuntimeError'>
Traceback (most recent call last):
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 641, in _io_thread_loop
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 733, in _read
  File "E:/xpra/xpra/net/websockets/protocol.py", line 109, in parse_ws_frame
RuntimeError: cannot handle fragmented 5 frames
2023-05-11 18:41:30,800 http_event_received(DataReceived(data=b'\x82SP\x00\x00\x02\x00\x00\x .. e', stream_id=15, stream_ended=False, push_id=0))
2023-05-11 18:41:30,800 Error parsing rencodeplus packet:
2023-05-11 18:41:30,801 XpraQuicConnection.close()
2023-05-11 18:41:30,801 ws:http_event_received(DataReceived(data=b'\x82SP\x00\x00\x02\x00\x00\x .. e', stream_id=15, stream_ended=False, push_id=0))
2023-05-11 18:41:30,801 Connection lost
2023-05-11 18:41:30,801  expected bytes, NoneType found
```

```2023-05-11 18:45:27,414 Error: read on XpraQuicConnection<0> failed: <class 'AssertionError'>
Traceback (most recent call last):
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 641, in _io_thread_loop
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 733, in _read
  File "E:/xpra/xpra/net/websockets/protocol.py", line 91, in parse_ws_frame
AssertionError: continuation frame does not follow a partial frame
2023-05-11 18:45:27,414 PushPromiseReceived: PushPromiseReceived(headers=[(b':method', b'CONNECT'), (b':scheme', b'wss'), (b':authority', b'0.0.0.0'), (b':path', b'/100')], push_id=0, stream_id=0)
2023-05-11 18:45:27,414 Error parsing rencodeplus packet:
2023-05-11 18:45:27,415 XpraQuicConnection.close()
2023-05-11 18:45:27,415 PushPromiseReceived headers: [(b':method', b'CONNECT'), (b':scheme', b'wss'), (b':authority', b'0.0.0.0'), (b':path', b'/100')]
2023-05-11 18:45:27,415 Connection lost
2023-05-11 18:45:27,416  expected bytes, NoneType found
```

```2023-05-11 18:45:22,853 error closing XpraQuicConnection<0>
Traceback (most recent call last):
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 641, in _io_thread_loop
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 668, in _write
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 689, in write_items
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 713, in write_buffers
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 724, in con_write
  File "E:/xpra/xpra/net/quic/client.py", line 76, in write
  File "E:/xpra/xpra/net/quic/connection.py", line 104, in write
  File "C:/msys64/mingw64/lib/python3.10/site-packages/aioquic/asyncio/protocol.py", line 103, in transmit
  File "C:/msys64/mingw64/lib/python3.10/asyncio/proactor_events.py", line 502, in sendto
AttributeError: 'NoneType' object has no attribute 'append'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 1203, in close
  File "E:/xpra/xpra/net/quic/connection.py", line 78, in close
  File "E:/xpra/xpra/net/quic/connection.py", line 85, in send_close
  File "E:/xpra/xpra/net/quic/client.py", line 76, in write
  File "E:/xpra/xpra/net/quic/connection.py", line 104, in write
  File "C:/msys64/mingw64/lib/python3.10/site-packages/aioquic/asyncio/protocol.py", line 103, in transmit
  File "C:/msys64/mingw64/lib/python3.10/asyncio/proactor_events.py", line 502, in sendto
AttributeError: 'NoneType' object has no attribute 'append'
```

For example, I am able to run `xeyes` and mouse over it, but trying to open Goland it loads the initial window but the client always crashes when I try to mouse over it.

**Comment by totaam** [comment] 2023-05-12 05:36
Can you try with: `XPRA_QUIC_SUBSTREAM_PACKET_TYPES=""` ?
I think I had seen this problem with `XPRA_QUIC_DATAGRAM_PACKET_TYPES` previously, which is why it is now disabled.

**Comment by totaam** [comment] 2023-05-12 09:16
> `2023-05-12 10:10:22,866 new quic stream 'window' started for window-icon`

This can only happen with `XPRA_QUIC_SUBSTREAM_PACKET_TYPES`
Try to make sure it is set to an empty string, or even an invalid value, ie: `XPRA_QUIC_SUBSTREAM_PACKET_TYPES=foo`

**Comment by jzyrobert** [comment] 2023-05-12 09:29
> > `2023-05-12 10:10:22,866 new quic stream 'window' started for window-icon`
> 
> This can only happen with `XPRA_QUIC_SUBSTREAM_PACKET_TYPES` Try to make sure it is set to an empty string, or even an invalid value, ie: `XPRA_QUIC_SUBSTREAM_PACKET_TYPES=foo`

Looks like having it empty doesn't work, setting it to foo worked. (I see you just made a commit for that).

The connection seems to work fine now but occasionally the client crashes with
```
2023-05-12 10:26:04,563 Fatal write error on datagram transport
protocol: <xpra.net.quic.client.WebSocketClient object at 0x000002421a30b8b0>
transport: <_ProactorDatagramTransport fd=2100 read=<_OverlappedFuture pending overlapped=<pending, 0x2423a4c3f40> cb=[_ProactorDatagramTransport._loop_reading()]> write=<_OverlappedFuture finished result=33>>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.10/asyncio/proactor_events.py", line 516, in _loop_writing
AssertionError
2023-05-12 10:26:04,603 Exception in callback QuicConnectionProtocol._handle_timer()
handle: <TimerHandle when=287886.6299652195 QuicConnectionProtocol._handle_timer()>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.10/asyncio/events.py", line 80, in _run
  File "C:/msys64/mingw64/lib/python3.10/site-packages/aioquic/asyncio/protocol.py", line 177, in _handle_timer
  File "C:/msys64/mingw64/lib/python3.10/site-packages/aioquic/asyncio/protocol.py", line 103, in transmit
  File "C:/msys64/mingw64/lib/python3.10/asyncio/proactor_events.py", line 502, in sendto
AttributeError: 'NoneType' object has no attribute 'append'
2023-05-12 10:26:04,618 write(b'\x82~\x00~P\x18\x00\x00\x00\x00\x00v\xc4\x8cin .. 87network\x86damage\x85state\x85batch\x86client', info-request) 130 bytes
2023-05-12 10:26:04,619 XpraQuicConnection.write(b'\x82~\x00~P\x18\x00\x00\x00\x00\x00v\xc4\x8cin .. 87network\x86damage\x85state\x85batch\x86client', info-request)
2023-05-12 10:26:04,619 XpraQuicConnection.stream_write(b'\x82~\x00~P\x18\x00\x00\x00\x00\x00v\xc4\x8cin .. 87network\x86damage\x85state\x85batch\x86client', info-request) using stream id 0
2023-05-12 10:26:04,619 Error: write on XpraQuicConnection<0> failed: <class 'AttributeError'>
Traceback (most recent call last):
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 641, in _io_thread_loop
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 668, in _write
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 689, in write_items
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 713, in write_buffers
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 724, in con_write
  File "E:/xpra/xpra/net/quic/client.py", line 76, in write
  File "E:/xpra/xpra/net/quic/connection.py", line 104, in write
  File "C:/msys64/mingw64/lib/python3.10/site-packages/aioquic/asyncio/protocol.py", line 103, in transmit
  File "C:/msys64/mingw64/lib/python3.10/asyncio/proactor_events.py", line 502, in sendto
AttributeError: 'NoneType' object has no attribute 'append'
2023-05-12 10:26:04,621 XpraQuicConnection.close()
2023-05-12 10:26:04,621 write(b'\x88\x02\x03\xe8', close) 4 bytes
2023-05-12 10:26:04,621 XpraQuicConnection.write(b'\x88\x02\x03\xe8', close)
2023-05-12 10:26:04,621 XpraQuicConnection.stream_write(b'\x88\x02\x03\xe8', close) using stream id 0
2023-05-12 10:26:04,622 error closing XpraQuicConnection<0>
Traceback (most recent call last):
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 641, in _io_thread_loop
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 668, in _write
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 689, in write_items
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 713, in write_buffers
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 724, in con_write
  File "E:/xpra/xpra/net/quic/client.py", line 76, in write
  File "E:/xpra/xpra/net/quic/connection.py", line 104, in write
  File "C:/msys64/mingw64/lib/python3.10/site-packages/aioquic/asyncio/protocol.py", line 103, in transmit
  File "C:/msys64/mingw64/lib/python3.10/asyncio/proactor_events.py", line 502, in sendto
AttributeError: 'NoneType' object has no attribute 'append'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 1203, in close
  File "E:/xpra/xpra/net/quic/connection.py", line 78, in close
  File "E:/xpra/xpra/net/quic/connection.py", line 85, in send_close
  File "E:/xpra/xpra/net/quic/client.py", line 76, in write
  File "E:/xpra/xpra/net/quic/connection.py", line 104, in write
  File "C:/msys64/mingw64/lib/python3.10/site-packages/aioquic/asyncio/protocol.py", line 103, in transmit
  File "C:/msys64/mingw64/lib/python3.10/asyncio/proactor_events.py", line 502, in sendto
AttributeError: 'NoneType' object has no attribute 'append'
2023-05-12 10:26:04,623 Connection lost
CONNECTION_LOST, reconnecting
```

(Thanks for all the help, I understand if QUIC isn't stable yet)

**Comment by totaam** [comment] 2023-05-12 09:29
My bad, I've just pushed a bunch of fixes - `XPRA_QUIC_SUBSTREAM_PACKET_TYPES=foo` should work until new builds are available.

**Comment by totaam** [comment] 2023-05-12 12:41
@jzyrobert can you try the [latest MS Windows beta builds](https://xpra.org/beta/windows/) with `-d quic`?
None of the workarounds using environment variables should be needed. (r33392 or later).

**Comment by jzyrobert** [comment] 2023-05-12 13:29
> @jzyrobert can you try the [latest MS Windows beta builds](https://xpra.org/beta/windows/) with `-d quic`? None of the workarounds using environment variables should be needed. (r33392 or later).

The connection starts up fine using r33387 on the server and 33392 on the client. However opening an app like Goland causes multiple kinds of crashes on the client side, for example:
```
2023-05-12 14:24:16,281 Error: read on XpraQuicConnection<0> failed: <class 'AssertionError'>
Traceback (most recent call last):
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 648, in _io_thread_loop
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 740, in _read
  File "E:/xpra/xpra/net/websockets/protocol.py", line 91, in parse_ws_frame
AssertionError: continuation frame does not follow a partial frame
2023-05-12 14:24:16,281 ws:http_event_received(DataReceived(data=b'P\x18\x00\x00\x00\x00\x00B\x .. a', stream_id=15, stream_ended=False, push_id=0))
2023-05-12 14:24:16,282 Error: received an invalid packet
2023-05-12 14:24:16,282 XpraQuicConnection.close()
2023-05-12 14:24:16,282 http_event_received(DataReceived(data=b'\x82\x7f\x00\x00\x00\x00\x00 .. H', stream_id=15, stream_ended=False, push_id=0))
2023-05-12 14:24:16,282  received uninterpretable nonsense: invalid packet header byte: 0x0000000000000000
2023-05-12 14:24:16,283 write(b'\x88\x02\x03\xe8', close) 4 bytes
2023-05-12 14:24:16,283 ws:http_event_received(DataReceived(data=b'\x82\x7f\x00\x00\x00\x00\x00 .. H', stream_id=15, stream_ended=False, push_id=0))
2023-05-12 14:24:16,283  b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x .. x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' (74 bytes)
2023-05-12 14:24:16,283 XpraQuicConnection.write(b'\x88\x02\x03\xe8', close)
2023-05-12 14:24:16,283 http_event_received(DataReceived(data=b'RIFF@M\x02\x00WEBPVP8L3M\x02 .. 0', stream_id=15, stream_ended=False, push_id=0))
2023-05-12 14:24:16,284  data: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

or
```
2023-05-12 14:26:19,957 Fatal write error on datagram transport
protocol: <xpra.net.quic.client.WebSocketClient object at 0x000001f899d73b50>
transport: <_ProactorDatagramTransport fd=3112 read=<_OverlappedFuture finished result=(b'c5}4\xb8\xa...6;o\xf9rC\xbf', ('127.0.0.1', 4000))> write=<_OverlappedFuture finished result=35> write_bufsize=5>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.10/asyncio/proactor_events.py", line 516, in _loop_writing
AssertionError
2023-05-12 14:26:19,957 XpraQuicConnection.write(b'\x82#P\x18\x00\x00\x00\x00\x00\x1b\xc7\x8fdamage-sequence?\x00\x97\x02\x12?\x01=\x00\x80', damage-sequence)
2023-05-12 14:26:19,958 XpraQuicConnection.stream_write(b'\x82#P\x18\x00\x00\x00\x00\x00\x1b\xc7\x8fdamage-sequence?\x00\x97\x02\x12?\x01=\x00\x80', damage-sequence) using stream id 0
2023-05-12 14:26:19,958 Error: write on XpraQuicConnection<0> failed: <class 'AttributeError'>
Traceback (most recent call last):
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 648, in _io_thread_loop
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 675, in _write
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 696, in write_items
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 720, in write_buffers
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 731, in con_write
  File "E:/xpra/xpra/net/quic/client.py", line 78, in write
  File "E:/xpra/xpra/net/quic/connection.py", line 106, in write
  File "C:/msys64/mingw64/lib/python3.10/site-packages/aioquic/asyncio/protocol.py", line 103, in transmit
  File "C:/msys64/mingw64/lib/python3.10/asyncio/proactor_events.py", line 502, in sendto
AttributeError: 'NoneType' object has no attribute 'append'
2023-05-12 14:26:19,959 XpraQuicConnection.close()
2023-05-12 14:26:19,959 Connection lost
2023-05-12 14:26:19,959 write(b'\x88\x02\x03\xe8', close) 4 bytes
2023-05-12 14:26:19,960 XpraQuicConnection.write(b'\x88\x02\x03\xe8', close)
2023-05-12 14:26:19,960 XpraQuicConnection.stream_write(b'\x88\x02\x03\xe8', close) using stream id 0
2023-05-12 14:26:19,975 Exception in callback QuicConnectionProtocol._handle_timer()
handle: <TimerHandle when=302301.7187620727 QuicConnectionProtocol._handle_timer()>
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.10/asyncio/events.py", line 80, in _run
  File "C:/msys64/mingw64/lib/python3.10/site-packages/aioquic/asyncio/protocol.py", line 177, in _handle_timer
  File "C:/msys64/mingw64/lib/python3.10/site-packages/aioquic/asyncio/protocol.py", line 103, in transmit
  File "C:/msys64/mingw64/lib/python3.10/asyncio/proactor_events.py", line 502, in sendto
AttributeError: 'NoneType' object has no attribute 'append'
```

or
```
2023-05-12 14:28:43,429 Error: received an invalid packet
2023-05-12 14:28:43,429 Warning unhandled websocket opcode 'f'
2023-05-12 14:28:43,430 XpraQuicConnection.write(w, (b'\x8a\nXL!6\xe79\x1e\xabZ\x86',))
2023-05-12 14:28:43,430 http_event_received(DataReceived(data=b'\x82\x7f\x00\x00\x00\x00\x00 .. 0', stream_id=15, stream_ended=False, push_id=0))
2023-05-12 14:28:43,430  received uninterpretable nonsense: invalid packet header byte: 0x9206779b43d9c9b1
2023-05-12 14:28:43,430 Error: read on XpraQuicConnection<0> failed: <class 'RuntimeError'>
Traceback (most recent call last):
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 648, in _io_thread_loop
  File "E:/xpra/xpra/net/protocol/socket_handler.py", line 740, in _read
  File "E:/xpra/xpra/net/websockets/protocol.py", line 109, in parse_ws_frame
RuntimeError: cannot handle fragmented 7 frames
2023-05-12 14:28:43,430 XpraQuicConnection.stream_write(w, (b'\x8a\nXL!6\xe79\x1e\xabZ\x86',)) using stream id 0
2023-05-12 14:28:43,431 ws:http_event_received(DataReceived(data=b'\x82\x7f\x00\x00\x00\x00\x00 .. 0', stream_id=15, stream_ended=False, push_id=0))
2023-05-12 14:28:43,433 http_event_received(DataReceived(data=b'RIFF\xa8#\x01\x00WEBPVP8L\x9 .. e', stream_id=15, stream_ended=False, push_id=0))
2023-05-12 14:28:43,431 XpraQuicConnection.close()
2023-05-12 14:28:43,431  b'\x92\x06w\x9bC\xd9\xc9\xb1\x85\xb7\xb9\xf5\xea .. \x80\x00\xcc\x0f\xf6;}\x85\x01\xde\x08C\xfb\xf5' (77 bytes)
2023-05-12 14:28:43,433 ws:http_event_received(DataReceived(data=b'RIFF\xa8#\x01\x00WEBPVP8L\x9 .. e', stream_id=15, stream_ended=False, push_id=0))
2023-05-12 14:28:43,433 write(b'\x88\x02\x03\xe8', close) 4 bytes
2023-05-12 14:28:43,433  data: '\x92\x06w\x9bCÙÉ±\x85·¹õêÉrßfNo\x00\x00`\x97f\xa0¼XþM©½+UçÒcÛî*\x00\x00\x00\x83®.Ì\x1dÝLÝ%\x13ªç÷\x06õL,.î_N\x80\x00Ì\x0fö;}\x85\x01Þ\x08Cûõ'
```

**Comment by totaam** [comment] 2023-05-13 11:38
@jzyrobert I can reproduce the problem easily enough by running `gtkperf -a` or even just typing in an xterm, but only with MS Windows clients.
Looks like a threading issue where the `ProactorDatagramTransport` isn't happy with us sending data from a different thread than the `asyncio` one..
Will come up with a fix.

**Comment by totaam** [comment] 2023-05-13 12:37
The commit above fixes the threading issues, only MS Windows clients need the update.
It's probably not too costly to switch threads to call `write()`, even on platforms that don't need it, at least compared to the cost of copying all the data.. which `asyncio` does.

I am closing this ticket because I am quite confident that the issue is resolved. Feel free to re-open if I've missed something.

**Closed by totaam** 2023-05-13 12:37 UTC
Labels: bug
