### ISSUE TITLE
Proxy ignores user configuration

### ISSUE THREAD

**Issue by ToppDev** [Xpra-org/xpra#3033] opened 2021-02-25 21:10 UTC
Hello,

I run xpra v4.1-r28309 on Ubuntu 20.04 as a proxy server and connect via browser to it.

The proxy runs as system service and starts new sessions itself. It has a sqlite database
```
------------------------------------------------------------------------------------------------
|    username|       password|         uid|         gid| displays| env options| session options|
------------------------------------------------------------------------------------------------
|        test|           user|   linuxuser|   linuxuser|         |            |                |
```

When I change the global config `/etc/xpra/conf.d/60_server.conf` and add a
```
start-after-connect = xterm
```
it opens when connecting. However when I edit the file `/home/linuxuser/.config/xpra/xpra.conf` it does not do anything.

Do I have the path wrong, or is the proxy not using the per-user settings?

**Comment by totaam** [comment] 2021-02-26 04:07
Is your proxy server running as root or as `linuxuser`?

> it opens when connecting

How do you connect? What command? Which client?

> ... it does not do anything.

Which particular option did you modify?

**Comment by ToppDev** [comment] 2021-02-26 07:19
The proxy is running as systemd-service, so it runs under root.

In `/etc/xpra/conf.d/60_server.conf` I have `start-after-connect = xterm`
And in `/home/linuxuser/.config/xpra/xpra.conf` I have `start-after-connect = firefox`

When I connect to the server with my client (xpra v4.0.6-r28285 on ArchLinux) with the following command, only the xterm is opened.
```
xpra attach tcp://test@192.168.1.186:10000/
```

**Comment by totaam** [comment] 2023-03-26 13:45
Looks like a duplicate of #1582.

**Closed by totaam** 2023-03-26 13:45 UTC
