### ISSUE TITLE
Stable proxy not working

### ISSUE THREAD

**Issue by MichaKersloot** [Xpra-org/xpra#4367] opened 2024-09-24 15:28 UTC
**Describe the bug**
Can't get stable version working. Tried on Ubuntu and Fedora

**To Reproduce**
1. install xpra
2. browse to http://server:14500/

Oh, you better disable SELinux as that will add some issues.

You get and error 400 on http://server:14500/ because certificates are not found:
edit `/etc/xpra/conf.d/12_ssl.conf`
change 
```
ssl-key = /etc/xpra/key.pem
ssl-cert = /etc/xpra/cert.pem
```

Find you now have a html5 client in your browser if you go to `https://server:14500/`  connecting to http still shows an error.

Now try to login and get an 'invalid username' error. 

edit `/etc/sysconfig/xpra` (or /etc/default/xpra)
change 
```
TCP_AUTH=sys:client-username=yes,verify-username=no
```

and now you can for example login with the option 'Start desktop' which really seems to start a new desktop on the server, but brings you back to the html5 login with an 'server closed connection'

On the server you'll find the following error:
`SocketProtocol._add_packet_to_queue() takes from 2 to 4 positional arguments but 7 were given`

And that error seems to be unsolvable for me ;-(

**System Information (please complete the following information):**
 - Server OS: Fedora 40
 - Client OS: Windows 11 / Firefox
 - Xpra Server Version : xpra v6.1.2-r1
 - Xpra Client Version: Xpra HTML5 Client Version 16.1

**Extra info**

I've been into this for some time now, so maybe I've changed a little bit more than stated above, but I don't think so.

**Comment by totaam** [comment] 2024-09-24 16:17
Sorry about this.
I think that you've hit a number of regressions that are due to be fixed in 6.1.3: https://github.com/Xpra-org/xpra/blob/v6.1.x/docs/CHANGELOG.md#613-2024-09-24 (under "proxy server")

Until this update is released, you have more luck with the 6.2 beta builds, or the 5.x LTS branch.

**Comment by totaam** [comment] 2024-09-25 11:06
> There also is a lot of documentation, although it's more for the current users than for newcomers like me ;-)

Documentation is very much a continuous work in progress.

> Is that because the proxy part is not used much and somehow got broken by some backport from beta?

There were a number of issues, not all of them would manifest themselves with all setups.

> Or did I got problems because I did not upgrade from an older version and installed it fresh?

No, upgrades should (usually) make no difference.

> I was not aware there is a 5.x LTS branch

This is documented!
https://github.com/Xpra-org/xpra/wiki/Versions

> Are there packages for that?

They are in the stable repository, which also contains newer builds from the 6.x series, so if you install using a default package manager command, you will get the newer builds.

**Comment by totaam** [comment] 2024-10-09 09:47
6.1.3 has been released with all the proxy fixes.

**Closed by totaam** 2024-10-09 09:47 UTC
Labels: bug, server, proxy
