### ISSUE TITLE
centos 8 yet another install issue

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3297] opened 2021-10-08 20:07 UTC
```
Package xpra-html5-4.5.2-1.r1056.el8.noarch.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```

**Comment by totaam** [comment] 2021-10-09 02:39
Sorry about that.

The good news is that I think I finally know what causes it: the build and the signing happen on different hosts, so if I sign some packages whilst the buildbot is still building more then it is possible for the repository timestamp to be newer than the packages it eventually contains and so the scripts don't re-generate the repository when they should.
The buildbot uploads preserve timestamps to prevent re-uploading things unnecessarily. I'll try to come up with a solution for that.

What is strange though is that I have force resigned all the packages - which takes quite a while, but `xpra-html5` was not one of the few packages that was missing the signature.
Perhaps you need a `dnf clean all`?

**Comment by totaam** [comment] 2021-11-05 14:03
I believe the issue is gone. Closing.

**Closed by totaam** 2021-11-05 14:03 UTC
Labels: packaging, linux

**Comment by totaam** [comment] 2023-07-18 17:16
GPG agent timeouts cause packages to be missed: https://github.com/Xpra-org/xpra/issues/3674#issuecomment-1640422672
