### ISSUE TITLE
MacOS shadowing almost doesn't work

### ISSUE THREAD

**Issue by nerzhulart** [Xpra-org/xpra#3567] opened 2022-06-27 18:09 UTC
**Describe the bug**
Shadow mode on MacOS starts  good but a connected client can do nothing except seeing an empty desktop, current app menu and moving a mouse.

Even mouse clicking doesn't work.
**To Reproduce**
1. server command ```xpra shadow --socket-dirs=~/.xpra --bind-tcp=0.0.0.0:10002```
2. client command ```xpra attch tcp://192.168.0.167:10002```

**System Information (please complete the following information):**
 - Server OS: MacOS Monterey 12.3.1
 - Client OS: Any. Tried on Win11 and Linux Manjaro with KDE. The same behavior
 - Xpra Server Version 4.3.3
 - Xpra Client Version 4.3.3

Server log output
```
~ xpra shadow --socket-dirs=~/.xpra --bind-tcp=0.0.0.0:10002
/bin/bash: python3.9: command not found
2022-06-27 21:07:12,822 Error 127 running source script '/etc/profile'
2022-06-27 21:07:12,923 created tcp socket '0.0.0.0:10002'

(Xpra:10456): Gtk-CRITICAL **: 21:07:13.274: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
2022-06-27 21:07:13,489 serving html content from '/Applications/Xpra.app/Contents/Resources/www'
2022-06-27 21:07:13,490 wrote pid 10456 to '$XDG_RUNTIME_DIR/xpra/Main/server.pid'
2022-06-27 21:07:13,495 Warning: socket directory '$XDG_RUNTIME_DIR/xpra/Main'
2022-06-27 21:07:13,495  expected permissions 0o700 but found 0o750
2022-06-27 21:07:13,508 created unix domain socket '/Users/artem.bukhonov/.xpra/UNIT-1333.local-Main'
2022-06-27 21:07:13,522 created unix domain socket '$XDG_RUNTIME_DIR/xpra/Main/socket'
2022-06-27 21:07:13,577 printer forwarding enabled using postscript
2022-06-27 21:07:13,680 32.0GB of system memory
2022-06-27 21:07:13,809 waiting for initialization thread to complete
2022-06-27 21:07:13,809 xpra is ready.
2022-06-27 21:07:14,259 GStreamer version 1.20.1 for Python 3.9.12 64-bit
2022-06-27 21:07:15,837 OpenGL is supported on display 'Main'
2022-06-27 21:07:15,837  using 'AMD Radeon Pro 555X OpenGL Engine' renderer
2022-06-27 21:07:19,690 New tcp connection received
2022-06-27 21:07:19,690  from '192.168.0.195:61833'
2022-06-27 21:07:19,690  on '0.0.0.0:10002'
2022-06-27 21:07:19,695 Handshake complete; enabling connection
2022-06-27 21:07:19,761 Error: failed to allocate a CUDA context:
2022-06-27 21:07:19,762  No module named 'pycuda'
2022-06-27 21:07:19,762  NVJPEG and NVENC will not be available
2022-06-27 21:07:19,762 Python/GTK3 Microsoft Windows 10 aero client version 4.3.3-r0 64-bit
2022-06-27 21:07:19,762  OpenGL is enabled with NVIDIA GeForce GTX 1080/PCIe/SSE2
2022-06-27 21:07:19,762  connected from 'DESKTOP-3RVDDUQ' as 'Nerzhul'
2022-06-27 21:07:19,764 shadow server: setting default keymap translation
2022-06-27 21:07:19,764  client root window size is 7680x2160
2022-06-27 21:07:19,769  automatic picture encoding enabled, also available:
2022-06-27 21:07:19,769   h264, vp9, vp8, png, png/P, png/L, webp, rgb24, rgb32, jpeg, jpega, scroll
2022-06-27 21:07:19,796 client   1 @02.281 Xpra shadow server version 4.3.3-r0 64-bit
2022-06-27 21:07:19,796 client   1 @02.281  running on Mac OS X 21.4.0
2022-06-27 21:07:19,797 client   1 @02.281  remote desktop size is 1680x1050
2022-06-27 21:07:19,797 client   1 @02.281 Attached to xpra server at tcp://192.168.0.167:10002/
2022-06-27 21:07:19,797 client   1 @02.281  (press Control-C to detach)
2022-06-27 21:07:20,249 client   1 @02.717 running, 1 window
2022-06-27 21:07:22,351 Error: cannot add printer 'OneNote for Windows 10':
2022-06-27 21:07:22,351  the printing system does not support application/pdf
2022-06-27 21:07:22,352 Error: cannot add printer 'Microsoft Print to PDF':
2022-06-27 21:07:22,352  the printing system does not support application/pdf
2022-06-27 21:07:36,502 xpra shadow version 4.3.3-r0 64-bit
2022-06-27 21:07:36,503  uid=502 (artem.bukhonov), gid=20 (staff)
2022-06-27 21:07:36,503  running with pid 10456 on Mac OS X 10.16
2022-06-27 21:07:36,506  on display 'Main' of size 1680x1050

```
[Short movie with this bug on youtube](https://www.youtube.com/watch?v=XDWMtvd2-7I)

**Comment by totaam** [comment] 2022-06-28 03:54
It is definitely a permission issue.
They've changed things so many times that I stopped counting.

This looks like a duplicate of #3425

**Closed** 2023-03-16 15:10 UTC
Labels: bug
