### ISSUE TITLE
Win11 client left Alt -> server Meta+Alt with Polish keyboard layout

### ISSUE THREAD

**Issue by filip-paczynski** [Xpra-org/xpra#4127] opened 2024-02-06 20:06 UTC
First of all, let me express my sincere admiration for the author(s) of Xpra - this is hands-down the best remote-work software available for Linux.

**Describe the bug**
While running linux server and windows 11 (or local Linux) client, a left `Alt` key on the client gets interpreted as `Meta+Alt` on the server, which makes some software difficult to use (especially IDEs, like IntelliJ IDEA)

**To Reproduce**
1. server command
   `/usr/bin/xpra start --exit-with-client=False --exit-with-children=True --start-child=xterm --attach=True --splash=True  --pixel-depth=24 --systemd-run=no --dpi=96 :50`
2. client command `xpra-Launcher.exe` with file containing:
  values in `<>` are substituted with my private values
  ```
  host=<SERVER>
  proxy_username=<WINDOWS_USER>
  password=<SERVER_PASS>
  min-quality=100
  proxy_port=22
  proxy_password=
  port=50
  autoconnect=False
  quality=100
  ssh_port=22
  username=<SERVER_USER>
  proxy_host=
  min-speed=1
  proxy_key=
  speed=0
  encoding=auto
  mode=ssh
  desktop-scaling=no
  modal-windows=True
  dpi=96
  keyboard-layout=en_US
  env=XPRA_EMULATE_ALTGR=0
  ```
4. specific action to trigger the bug
Launch IntelliJ IDEA, or any other software capable of intercepting keyboard shortcuts, try to use a shortcut involving left `Alt` key, observe that the software used interprets it as `Meta+Alt` instead of `Alt`.

**System Information (please complete the following information):**
 - Server OS: OpenSuse Leap 15.5
 - Client OS: Windows 11, also OpenSuse Leap 15.5
 - Xpra Server Version v6.0-r34478M (ga3c265d6) beta
 - Xpra Client Version v6.0.r34778 (g1db7fbad2), also tried with most recent beta, and 5.0.4 stable
 - ![image](https://github.com/Xpra-org/xpra/assets/1962070/073c1704-349c-4df9-9ebf-854858d1bb6d)
 - source of server packages: https://build.opensuse.org/package/show/home%3Asbradnick%3Axpra-python311/xpra

**Additional context**
- I do not care about opengl, sound, or printers

***Following guide from https://github.com/Xpra-org/xpra/blob/master/docs/Features/Keyboard.md***
- Common issues section - I either do not understand these issues or find the solutions difficult to interpret/apply 
- In general, I think t would be helpful to divide steps mentioned under https://github.com/Xpra-org/xpra/blob/master/docs/Features/Keyboard.md#reporting-bugs between server/client tasks

***try the keyboard debugging tool found in the xpra toolbox***
- on the server, or on the client?
- on the server, using xterm launched in xpra session:
  - it doesn't close properly on windows client
  - Ignoring this, upon launching terminal shows:
  ```
  /usr/lib64/python3.11/site-packages/xpra/gtk/dialogs/toolbox.py:54: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.set_wmclass("xpra-toolbox", "Xpra-Toolbox")
  ```
  - after pressing `Alt` on windows 11 client, it looks like this:
    ![image](https://github.com/Xpra-org/xpra/assets/1962070/578e930a-bd00-4ee4-84a0-5801cefc4892)

***active keyboard layout(s)***
- I only use one keyboard layout (Polish programmer's on windows (client) side, and similar on linux (server) side)

***input methods***
- I do not understand how to provide info on this

***keyboard related configuration setup/files***
- I did not customize any of these

***keyboard type***
- physically a standard international/US keyboard, "logically" the right `Alt` functions as `AltGr` or `Ctrl+Alt` on windows

***client and server [log output](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Logging.md) with the -d keyboard debugging switch***
- Server:
  launch cmd: `/usr/bin/xpra start --exit-with-client=False --exit-with-children=True --start-child=xterm --attach=True --splash=True  --pixel-depth=24 --systemd-run=no --dpi=96 :50 -d keyboard`
    
At this point, possibly due to my other attempts in `/etc/xpra` left `Alt` started working properly, but I lost access to Polish-specific letters, which are entered via (right) `AltGr+LETTER`.

I also realized, that I'd need to setup Xpra on a VM to avoid restarts and keep my "debugging" config separate from "work" config.  
I shall update this issue when I get the chance to test with VM.

Sorry for incomplete issue description.

**Comment by filip-paczynski** [comment] 2024-02-06 20:07
sprry, pressed "enter" by mistake :(

**Comment by totaam** [comment] 2024-02-07 02:20
Too much information missing.
Please add the details and check for existing duplicates.

**Comment by filip-paczynski** [comment] 2024-02-07 21:13
> Too much information missing. Please add the details and check for existing duplicates.

Yes, sorry, I mistakenly pressed `CTRL+ENTER` and it got sent prematurely.

**Comment by filip-paczynski** [comment] 2024-02-07 21:36
After executing `xpra upgrade` + `xpra recover` in an attempt to get rid of windows not disappearing on the client after closing them:
- left `Alt` stopped working
- `pl` keyboard layout still doesn't work (no "special" Polish letters) - however this might be due to some edits under `/etc/xpra`

I will review my changes in `/etc/xpra` tomorrow - probably.

**Comment by totaam** [comment] 2024-02-08 04:01
> `--exit-with-client=False`

No need for this, it is the default.

> `--splash=True`

Same.
> `--pixel-depth=24`

Same.
> `--systemd-run=no`

Why is this needed?
> `--dpi=96`

This is only needed when Xdummy isn't being used, which may be the case on suse - I don't know.

> `min-quality=100`
> (..)
> `quality=100`

Don't specify both.
> try to use a shortcut involving left `Alt` key, observe that the software used interprets it as `Meta+Alt` instead of `Alt`

I'm pretty sure that we have other tickets for this issue.

> on the server, using xterm launched in xpra session:
> it doesn't close properly on windows client

Do you mean that the window does not close? I have never seen that and this is something I do hundreds of times a day..
Try a newer build, 6.0 is in beta.

> Ignoring this, upon launching terminal shows:
> `/usr/lib64/python3.11/site-packages/xpra/gtk/dialogs/toolbox.py:54: DeprecationWarning: Gtk.Window.set_wmclass is deprecated`
> `self.set_wmclass("xpra-toolbox", "Xpra-Toolbox")`

This is already silenced in the latest 6.0 beta builds. Try a newer version.

When running locally, try `--keyboard-raw=yes`.
MS Windows clients are much more difficult to map to X11 key events.

**Comment by filip-paczynski** [comment] 2024-02-08 18:10
Upon connecting from Windows 11 using config file:
```
host=<REDACTED>
proxy_username=<REDACTED>
password=<REDACTED>
proxy_port=22
proxy_password=
port=50
autoconnect=False
quality=100
ssh_port=22
username=<REDACTED>
proxy_host=
min-speed=1
proxy_key=
speed=0
encoding=auto
mode=ssh
desktop-scaling=no
modal-windows=False
dpi=96
```
- Left `Alt` no longer works properly - gets interpreted as `Alt+Meta` for example, pressing `Alt+1` results in:
  ![image](https://github.com/Xpra-org/xpra/assets/1962070/143bded6-2468-4e83-952c-9a765df1c0a6)
- `AltGr` works properly (for special PL letters)
- `~` shows up as `}`

After adding `input-method=none` to the config file: same results.

What can I do to help You debug this?

**Comment by totaam** [comment] 2024-02-09 03:23
> After adding `input-method=none` to the config file: same results.

Input method is used when starting the session, not when connecting to it.

> Left `Alt` no longer works properly - gets interpreted as `Alt+Meta` ...

Does this happen every time or only when connecting a second time?

Is this a duplicate of one of these tickets: [#4066](https://github.com/Xpra-org/xpra/issues/4066#issuecomment-1901059501), #3675 ?
See also: https://github.com/Xpra-org/xpra/issues/2946#issuecomment-845137724

**Comment by filip-paczynski** [comment] 2024-02-09 19:28
> Does this happen every time or only when connecting a second time?
- First time connecting either from windows, or linux: left `Alt` works fine
- Second+ time connecting: left `Alt` stops working properly

> Is this a duplicate of one of these tickets: https://github.com/Xpra-org/xpra/issues/4066#issuecomment-1901059501, https://github.com/Xpra-org/xpra/issues/3675 ?
- #4066 seems very familiar, so - yes

> See also: https://github.com/Xpra-org/xpra/issues/2946#issuecomment-845137724
- I've put `env=XPRA_EMULATE_ALTGR=0` into my client-side .xpra file - no change

I will try to compile 5.0.5 on server side and report back.

PS
The issue with non-closing windows went away after downgrading windows client to stable (5.0.4, 5.0.5)

**Comment by totaam** [comment] 2024-02-10 08:10
> First time connecting either from windows, or linux: left Alt works fine

OK, so this is a duplicate of #4066 - please subscribe to that one.

> I tried the latest version of 5.x available from opensuse repos/build service, which is 5.0r33693M

"latest" - that's incredibly out of date.

> The issue with non-closing windows went away after downgrading windows client to stable

You must have been unlucky with the beta version you were running.

**Closed by totaam** 2024-02-10 08:10 UTC
Labels: bug, duplicate
