### ISSUE TITLE
sudo apt update fails with the xpra repository

### ISSUE THREAD

**Issue by fshsweden** [Xpra-org/xpra#4001] opened 2023-09-13 13:40 UTC
**Describe the bug**
sudo apt update fails with the xpra repository

**To Reproduce**
```
sudo wget -O "/usr/share/keyrings/xpra.asc" https://xpra.org/xpra.asc
cd /etc/apt/sources.list.d
sudo wget https://raw.githubusercontent.com/Xpra-org/xpra/master/packaging/repos/jammy/xpra.sources
sudo apt update
```
result:
```
Get:30 https://xpra.org focal/main amd64 Packages [5 871 B]
Err:30 https://xpra.org focal/main amd64 Packages
  File has unexpected size (6988 != 5871). Mirror sync in progress? [IP: 78.129.163.65 443]
  Hashes of expected file:
   - Filesize:5871 [weak]
   - SHA512:b828f9ad7bc4aa7d239a0f4613f6015cfcf99fce5f0b53423c3c4d233203de068ce707b6fcec44e3dbea548f681bb19bef6fbfdbf61e3d5f01487e6c117496e9
   - SHA256:b9133a08dcc2ebd24e858fa55d92d1021b29ff1f10d394fe67a360ecf4c4fe9b
   - SHA1:28cfc1d2b1b60b3283041e41221db49f7f8e513e [weak]
   - MD5Sum:6003a5309b9c17b05d24d26cd7efcdfa [weak]
  Release file created at: Sat, 02 Sep 2023 09:59:26 +0000
Get:31 https://xpra.org focal/main arm64 Packages [5 884 B]
Fetched 15,7 kB in 3s (4 938 B/s)         
Reading package lists... Done
E: Failed to fetch https://xpra.org/dists/focal/main/binary-amd64/Packages.bz2  File has unexpected size (6988 != 5871). Mirror sync in progress? [IP: 78.129.163.65 443]
   Hashes of expected file:
    - Filesize:5871 [weak]
    - SHA512:b828f9ad7bc4aa7d239a0f4613f6015cfcf99fce5f0b53423c3c4d233203de068ce707b6fcec44e3dbea548f681bb19bef6fbfdbf61e3d5f01487e6c117496e9
    - SHA256:b9133a08dcc2ebd24e858fa55d92d1021b29ff1f10d394fe67a360ecf4c4fe9b
    - SHA1:28cfc1d2b1b60b3283041e41221db49f7f8e513e [weak]
    - MD5Sum:6003a5309b9c17b05d24d26cd7efcdfa [weak]
   Release file created at: Sat, 02 Sep 2023 09:59:26 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
**System Information (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Client OS: Linux Mint
 - Xpra Server Version <failed to install>
 - Xpra Client Version <failed to install>

**Additional context**

Installation worked earlier today on another Ubuntu 22.04 server

**Comment by totaam** [comment] 2023-09-14 02:31
Sorry about that, it was a permission issue which prevented the repo files from being re-generated.

Should be fixed now, just try again.

**Closed by totaam** 2023-09-14 02:31 UTC
Labels: bug

**Comment by fshsweden** [comment] 2023-09-14 12:06
It works now, thanks!

**Comment by polygonnedpotato** [comment] 2023-11-05 23:39
it appears that this is occurring again.
```
Hit:1 http://security.debian.org/debian-security testing-security InRelease
Hit:2 https://dl.winehq.org/wine-builds/debian trixie InRelease
Hit:3 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:4 http://deb.debian.org/debian sid InRelease
Hit:5 https://packages.microsoft.com/debian/11/prod nightly InRelease
Hit:6 http://deb.debian.org/debian unstable InRelease
Hit:7 http://deb.debian.org/debian experimental InRelease
Hit:8 https://packages.microsoft.com/debian/12/prod nightly InRelease
Hit:9 https://packages.microsoft.com/debian/12/prod bookworm InRelease
Hit:10 http://security.debian.org/debian-security trixie-security InRelease
Hit:11 http://deb.debian.org/debian testing InRelease
Hit:12 http://deb.debian.org/debian-debug sid-debug InRelease
Hit:13 http://deb.debian.org/debian-debug unstable-debug InRelease
Hit:14 http://deb.debian.org/debian-debug testing-debug InRelease
Hit:15 http://deb.debian.org/debian-debug experimental-debug InRelease
Hit:16 https://www.deb-multimedia.org sid InRelease
Hit:18 https://deb-multimedia.org trixie InRelease
Hit:19 http://deb.debian.org/debian testing-updates InRelease
Hit:20 http://deb.debian.org/debian testing-proposed-updates InRelease
Hit:21 https://www.deb-multimedia.org experimental InRelease
Hit:22 http://deb.debian.org/debian testing-backports InRelease
Hit:23 https://www.deb-multimedia.org testing InRelease
Get:17 https://xpra.org/beta sid InRelease [4,769 B]
Hit:24 http://deb.debian.org/debian trixie InRelease
Hit:25 http://deb.debian.org/debian-debug trixie-debug InRelease
Hit:26 https://www.deb-multimedia.org unstable InRelease
Hit:27 http://deb.debian.org/debian trixie-updates InRelease
Hit:28 http://deb.debian.org/debian trixie-proposed-updates InRelease
Hit:29 http://deb.debian.org/debian trixie-backports InRelease
Get:30 https://xpra.org/beta sid/main amd64 Packages [26.0 kB]
Err:30 https://xpra.org/beta sid/main amd64 Packages
  File has unexpected size (36916 != 26038). Mirror sync in progress? [IP: 78.129.163.65 443]
  Hashes of expected file:
   - Filesize:26038 [weak]
   - SHA512:c2d1b791b9fd0054e840fb781f21a085efda5b1336e148522cec53558dd87e7cbac477b15becf4160ca671911cec4377fdac5c5f98d5b0cdfb5220c6d8e7716d
   - SHA256:f95f6a28c0a099bc7f2564d2614e4c3972983fa42699a5af588d41986b6f0414
   - SHA1:4922320b048db342578d39ef2b5cca07a39d5354 [weak]
   - MD5Sum:ecc8cb3668bab9361d9126a7168bbac8 [weak]
  Release file created at: Mon, 16 Oct 2023 08:51:32 +0000
Fetched 4,769 B in 4s (1,342 B/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://deb.nodesource.com/node_20.x nodistro InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://packages.microsoft.com/debian/11/prod nightly InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://packages.microsoft.com/debian/12/prod nightly InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://xpra.org/beta sid InRelease' doesn't support architecture 'arm64'
E: Failed to fetch https://xpra.org/beta/sid/main/binary-amd64/Packages.bz2  File has unexpected size (36916 != 26038). Mirror sync in progress? [IP: 78.129.163.65 443]
   Hashes of expected file:
    - Filesize:26038 [weak]
    - SHA512:c2d1b791b9fd0054e840fb781f21a085efda5b1336e148522cec53558dd87e7cbac477b15becf4160ca671911cec4377fdac5c5f98d5b0cdfb5220c6d8e7716d
    - SHA256:f95f6a28c0a099bc7f2564d2614e4c3972983fa42699a5af588d41986b6f0414
    - SHA1:4922320b048db342578d39ef2b5cca07a39d5354 [weak]
    - MD5Sum:ecc8cb3668bab9361d9126a7168bbac8 [weak]
   Release file created at: Mon, 16 Oct 2023 08:51:32 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by totaam** [comment] 2023-11-06 04:00
Sorry about that, no disk space problems this time so I don't know what caused it.
I have re-generated all the indexes.

**Comment by polygonnedpotato** [comment] 2023-11-11 21:35
sorry again, but yet again, it happened :(

perhaps, there should be a job that periodically regenerates the index files? at least until the issue can be resolved.

**Comment by totaam** [comment] 2023-11-12 04:57
> perhaps, there should be a job that periodically regenerates the index files?

No, those are signed with my GPG key, I need to enter the passphrase.

I think that the problem is related to gpg agent forwarding.
That thing is so fundamentally broken it's completely unusable.
At the best of times I get a prompt, other times it garbles some random terminal, other times it fails silently.

I have re-generated the repo data.

**Comment by jzyrobert** [comment] 2023-11-28 11:53
@totaam This seems to have happened again now, please could you update the files again?
(The packages.* files updated but not the Inrelease)

Thanks

**Comment by totaam** [comment] 2023-11-28 11:59
@jzyrobert which distro version or URL was this?
I have force-deleted the `*Release*` and `*Packages*` files to ensure they get re-generated, and verified that `gpg_agent` is requesting the key.

**Comment by nakkaya** [comment] 2023-11-29 13:52
@totaam This is also happening in Debian 12 (Bookworm), on a fresh install.

**Comment by totaam** [comment] 2023-11-29 15:21
@nakkaya I've just re-generated the repo data, again.
`gpg` agent forwarding is just rubbish, I'm going to have to find another way and sign things locally where the keys are.

**Comment by totaam** [comment] 2023-12-03 08:55
FYI: I've changed my repository scripts to download and sign the packages locally instead of using the broken gpg agent forwarding that was causing so many problems.

**Comment by totaam** [comment] 2024-03-22 03:06
https://github.com/Xpra-org/xpra/issues/4170#issuecomment-2014260048
