### ISSUE TITLE
Default service file is misconfigured on ubuntu focal

### ISSUE THREAD

**Issue by Mazwak** [Xpra-org/xpra#3200] opened 2021-07-13 15:47 UTC
Hi

I’m testing xpra and xpra-html5.

The first problem I ran into is that the service file is misconfigured.

The “`EnvironmentFile`” property points to `/etc/sysconfig/xpra`.

But on Debian and Ubuntu, it is `/etc/default/xpra`

So by default, the service fails to start with an elusive message :
```
cannot load authentication module '' for '': No module named 'xpra.server.auth._auth'
```
because `$TCP_AUTH` is empty.

**Comment by basilgello** [comment] 2021-07-13 16:01
Look at my Debian Salsa repos: https://salsa.debian.org/basilgello/xpra and https://salsa.debian.org/basilgello/xpra-html5

**Comment by totaam** [comment] 2021-07-13 16:12
@Mazwak please specify which version you are using and the full distro - as this should not be the case.

**Comment by totaam** [comment] 2021-07-13 16:14
The detection logic between `/etc/sysconfig` and `/etc/default` can be found here: 4d5b3087a2e101b05131707b4a1459303644ab84

**Comment by Mazwak** [comment] 2021-07-13 16:15
I’m using Ubuntu 20.04 desktop, as the title says (focal). And default xpra repo.

deb https://xpra.org/ focal main

System was installed, updated and xpra was added.

**Comment by totaam** [comment] 2021-07-13 16:31
With the beta repo, I am seeing the correct value:
```
$ grep Environment /lib/systemd/system/xpra.service
EnvironmentFile=-/etc/default/xpra
```
But not with the stable repo, which is strange because the same changeset exists there too: 4d5b3087a2e101b05131707b4a1459303644ab84

@basilgello any ideas?

**Comment by basilgello** [comment] 2021-07-13 16:50
@Mazwak can you run the following reproducer on your Ubuntu?

```python
import sys
if sys.version_info<(3, 6):
    raise Exception("xpra no longer supports Python versions older than 3.6")

import os.path
import xpra
from xpra.os_util import (
    get_status_output, load_binary_file, get_distribution_version_id,
    BITS, WIN32, OSX, LINUX, POSIX, NETBSD, FREEBSD, OPENBSD,
    is_Ubuntu, is_Debian, is_Fedora, is_CentOS, is_RedHat,
    )

cdir = "N/A"
if is_RedHat() or is_CentOS() or is_Fedora():
    cdir = "/etc/sysconfig"
elif is_Debian() or is_Ubuntu():
    cdir = "/etc/default"
elif os.path.exists("/etc/sysconfig"):
    cdir = "/etc/sysconfig"
else:
    cdir = "/etc/default"

print("cdir = " + cdir)
```

**Comment by totaam** [comment] 2021-07-13 17:12
@basilgello I've tried it and it works properly.
My guess is that some package is installed in one case and not the other and that causes the detection to change.
I've built a container by hand to run this script and it detected correctly.
No idea why the buildbot did not..

**Comment by basilgello** [comment] 2021-07-13 17:17
Interesting what @Mazwak shows us, too :)

**Comment by totaam** [comment] 2021-07-13 17:40
> Interesting what @Mazwak shows us, too :)

I'll bet that it's going to give the correct answer.
The real question is why does the buildbot get a different answer.

**Comment by Mazwak** [comment] 2021-07-15 13:32
I get "/etc/default". I checked it was from the "debian" if.

I installed a clean ubuntu, no updates, add repo, install xpra.
Script says "/etc/default"
Service is configured with "/etc/sysconfig"

**Comment by Mazwak** [comment] 2021-07-15 13:58
I also tested "copytodir" and substitution. It seems OK, replacing path in the service file.

**Comment by basilgello** [comment] 2021-07-15 14:49
Then I guess @totaam needs to fix his container :)

**Comment by totaam** [comment] 2021-07-15 14:50
> Then I guess @totaam needs to fix his container :)

I do, problem is that I have no idea what is different:
https://github.com/Xpra-org/repo-build-scripts

**Comment by basilgello** [comment] 2021-07-15 15:40
> I have no idea what is different

If you have a presumably faulty container image, `podman mount` it and the correct image to different subfolders of `/tmp` then do `diff -ru` excluding `/dev`, `/proc`, `/sys`

**Comment by Mazwak** [comment] 2021-07-15 16:03
Moreover, the debian packaging has a patch just for this. Not sure how it works, or if it works.

The very strange part is that setup puts 'xpra' file in /etc/default.

I wonder if the service file is copied over from somewhere else.

**Comment by basilgello** [comment] 2021-07-15 16:27
It is part of onlyjob's maintenance work :)

**Comment by totaam** [comment] 2021-07-16 04:09
> I wonder if the service file is copied over from somewhere else.

Thanks for the hint @Mazwak

Now I remember doing something like this before, we have a debian specific service file: https://github.com/Xpra-org/xpra/blob/master/packaging/debian/xpra/xpra.service

And somehow it seems that it was reverted to the default `/etc/sysconfig`.
That's now fixed.

**Closed by totaam** 2021-07-16 04:09 UTC
Labels: bug, packaging
