### ISSUE TITLE
/etc/xdg/menus/kde-debian-menu.menu is missing in bullseye

### ISSUE THREAD

**Issue by alexbodn** [Xpra-org/xpra#3787] opened 2023-03-06 18:33 UTC
**Describe the bug**
i don't know whether this is a bug in xpra.
i'm talking of the version you provide for debian bullseye.
/etc/xdg/menus/kde-debian-menu.menu is missing in debian bullseye.
i hope my solution was good enough, linked the missing file to xfce-applications.menu.

**Comment by totaam** [comment] 2023-03-07 02:39
My guess is that a42e2343ee572ff2edb28ece0b38904969c75470 fixes your problem - duplicate of #2174.

**Comment by alexbodn** [comment] 2023-03-07 07:21
yes it seems it would find xfce-applications.menu

**Closed** 2023-03-07 08:07 UTC
Labels: bug, server, linux
