### ISSUE TITLE
Trying to type `&` with `de` keyboard layout results in `K`

### ISSUE THREAD

**Issue by Voros-Roka** [Xpra-org/xpra#4404] opened 2024-10-26 19:39 UTC
**Describe the bug**
When trying to type `&`, `shift+6` with a `de` keyboard layout on client, `K` is inserted instead. 

**To Reproduce**

 1. server command: `xpra start :0 --uid=1000 --gid=1000 --mdns=no --exit-with-client=no --exit-with-children=no --exit-with-windows=no --daemon=no --mmap=/sys/devices/pci0000:00/0000:00:08.0/resource2_wc --bind-vsock=auto:2000`
 2. client command: `XPRA_USE_NATIVE_TRAY=0 xpra attach vsock://4:2000 --mmap=/dev/shm/my-ivshmem --border=red,8 --opengl=no --sharing=yes`
 3. Pressing `shift+6` to type `&` with `de` keyboard layout on server and client

**System Information (please complete the following information):**

 - Server OS: Artix Linux
 - Client OS: Artix Linux
 - Xpra Server Version: `commit gce124c6415 from master branch`
 - Xpra Client Version: `commit g75d2762385 from v6.2.x branch`

**Additional context**
The server runs with xdummy inside a qemu vm. LightDM is the display manager and AwesomeWM the window manager both on server and client. There is no compositing involved. xpra is set to keyboard layout `auto` in the menu. While testing commit ce124c6415 (on server) for issue https://github.com/Xpra-org/xpra/issues/4403 i noticed that when i am trying to type `&` (`shift+6`) with a `de` keyboard layout (`setxkbmap de` on client) i get a `K` instead. This did definitely not happen with 75d2762385 or any previous version as server. I tried ce124c6415 and 75d2762385 as clients but there was no difference, i still got `K` instead of `&`. `xpra toolbox` -> keyboard shows the following for pressing the `6` without `shift`:

```
down 6                            '6'   54        15     0 0    2
up   6                            '6'   54        15     0 0    2
```
and for `shift+6`:

 ```
down Shift_L                      ''    65505     50     0 0    S
down K                            'K'   75        45     0 0    S, 2
up   K                            'K'   75        45     0 0    S, 2
```

That got me curious and i tried different combinations that resulted in the following table (N/A means that while pressing the key nothing happened):

| `setxkbmap` client | `setxkbmap` server | `shift+6` expected | `shift+6` actual | `shift+7` expected | `shift+7` actual |
| --- | --- | --- | --- | --- | --- |
| `de` | `de` | `&` | `K` | `/` | `/` |
| `de` | `us` | `&` | `K` | `/` | `&` |
| `us` | `us` | `^` | `^` | `&` | `K` |
| `us` | `de` | `^` | N/A | `&` | `K` |

Something between commit 75d2762385 and ce124c6415 changed that leads to that behavior. Even if we disregard mismatched layouts between server and client there is definitly something wrong. I did not notice any problems with other keys. Sadly i am currently not able to provide more information then that, but as soon as i am able to what can i provide to help with debugging?

**Comment by totaam** [comment] 2024-10-27 02:30
Likely a duplicate of #4396

The commit has been reverted in v6.2.x

I'm trying to find a better solution for git master.

**Comment by totaam** [comment] 2024-11-23 15:10
@Voros-Roka is this still a problem?
I think 730e45eb41bb38aa8e75e0bb3c78f3339910c11e is the correct fix (server side).

**Closed** 2024-12-10 08:54 UTC
Labels: bug, keyboard

**Comment by Voros-Roka** [comment] 2025-01-08 12:51
Sorry for replying so late. Was not able to do any testing until now. Yes, everything works now!
